(function(){
var C=window.AFC_CONFIG||{};var lc=null;try{lc=window.localStorage}catch(e){}
function cfg(k){if(lc){var v=lc.getItem("calcverse:"+k);if(v!==null&&v!=="")return v;}return C[k];}
var premium=lc&&lc.getItem("afc-premium")==="1";
// GA4
var ga=cfg("gaId");if(ga){var s=document.createElement("script");s.async=true;s.src="https://www.googletagmanager.com/gtag/js?id="+ga;document.head.appendChild(s);window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};gtag("js",new Date());gtag("config",ga);}
// AdSense
var pub=cfg("adsenseClient");if(pub&&!premium&&C.adsEnabled!==false){var a=document.createElement("script");a.async=true;a.setAttribute("crossorigin","anonymous");a.src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client="+pub;document.head.appendChild(a);if(C.autoAds!==false){try{(window.adsbygoogle=window.adsbygoogle||[]).push({google_ad_client:pub,enable_page_level_ads:true});}catch(e){}}try{var ins=document.querySelectorAll("ins.adsbygoogle");for(var i=0;i<ins.length;i++){(window.adsbygoogle=window.adsbygoogle||[]).push({});}}catch(e){}}
// recent tools
try{var path=location.pathname,ti=(document.title||"").split("|")[0].trim();if(lc&&path&&path!=="/"&&ti){var R=JSON.parse(lc.getItem("afc-recent")||"[]");R=R.filter(function(x){return x.u!==path});R.unshift({u:path,t:ti});R=R.slice(0,24);lc.setItem("afc-recent",JSON.stringify(R));}}catch(e){}
// styles
var css="#afc-fab{position:fixed;right:14px;bottom:14px;display:flex;flex-direction:column;gap:8px;z-index:9000}#afc-fab button{width:44px;height:44px;border-radius:50%;border:none;background:#4f46e5;color:#fff;font-size:17px;cursor:pointer;box-shadow:0 4px 12px rgba(0,0,0,.22)}#afc-install{position:fixed;left:0;right:0;bottom:0;background:#111827;color:#fff;display:flex;align-items:center;gap:12px;justify-content:center;padding:12px;z-index:9500;font-family:system-ui,Arial}#afc-install button{border:none;border-radius:8px;padding:8px 14px;font-weight:700;cursor:pointer}#afc-i-yes{background:#4f46e5;color:#fff}#afc-i-no{background:transparent;color:#9aa}#afc-aff{margin:24px 0;padding:16px;border:1px dashed #c7d2fe;border-radius:12px;text-align:center;background:#eef2ff;color:#334155;font-size:.95rem}";var st=document.createElement("style");st.textContent=css;document.head.appendChild(st);
// FAB share + favorite
function fab(){if(!document.body||document.getElementById("afc-fab"))return;var isFav=false;try{var F=JSON.parse(lc.getItem("afc-fav")||"[]");isFav=F.some(function(x){return x.u===location.pathname});}catch(e){}var bar=document.createElement("div");bar.id="afc-fab";bar.innerHTML='<button data-a="fav" title="Save">'+(isFav?"\u2605":"\u2606")+'</button><button data-a="wa" title="WhatsApp">\ud83d\udcac</button><button data-a="tw" title="Share on X">\ud835\udd4f</button><button data-a="cp" title="Copy link">\ud83d\udd17</button>';document.body.appendChild(bar);bar.addEventListener("click",function(e){var b=e.target.closest?e.target.closest("button"):null;if(!b)return;var a=b.getAttribute("data-a"),u=location.href,t=document.title;if(a==="wa")window.open("https://wa.me/?text="+encodeURIComponent(t+" "+u),"_blank");else if(a==="tw")window.open("https://twitter.com/intent/tweet?text="+encodeURIComponent(t)+"&url="+encodeURIComponent(u),"_blank");else if(a==="cp"){try{navigator.clipboard.writeText(u);b.textContent="\u2713";setTimeout(function(){b.textContent="\ud83d\udd17"},1200);}catch(e){}}else if(a==="fav"){try{var F=JSON.parse(lc.getItem("afc-fav")||"[]");var i=-1;for(var j=0;j<F.length;j++){if(F[j].u===location.pathname){i=j;break;}}if(i>=0){F.splice(i,1);b.textContent="\u2606";}else{F.unshift({u:location.pathname,t:(document.title||"").split("|")[0].trim()});b.textContent="\u2605";}lc.setItem("afc-fav",JSON.stringify(F));}catch(e){}}});}
if(document.readyState!=="loading")fab();else document.addEventListener("DOMContentLoaded",fab);
// affiliate banner
function aff(){if(!(C.affiliate&&C.affiliate.enabled&&C.affiliate.html)||premium)return;var m=document.querySelector("main")||document.body;if(m&&!document.getElementById("afc-aff")){var d=document.createElement("div");d.id="afc-aff";d.innerHTML=C.affiliate.html;m.appendChild(d);}}
if(document.readyState!=="loading")aff();else document.addEventListener("DOMContentLoaded",aff);
// PWA install prompt
window.addEventListener("beforeinstallprompt",function(e){e.preventDefault();var dp=e;if(lc&&lc.getItem("afc-install-dismiss")==="1")return;if(document.getElementById("afc-install"))return;var ib=document.createElement("div");ib.id="afc-install";ib.innerHTML='<span>\ud83d\udcf2 Install allfreecalculators.in</span><button id="afc-i-yes">Install</button><button id="afc-i-no">\u2715</button>';document.body.appendChild(ib);document.getElementById("afc-i-yes").onclick=function(){dp.prompt();ib.remove();};document.getElementById("afc-i-no").onclick=function(){if(lc)lc.setItem("afc-install-dismiss","1");ib.remove();};});
})();
(function(){var lc;try{lc=localStorage}catch(e){return}var p=location.pathname;if(p==="/"||p.indexOf("/blog/")===0||p.indexOf("/category/")===0)return;if(!/^\/[^/]+\/[^/]+\//.test(p))return;
function draw(){var m=document.querySelector("main");if(!m||document.getElementById("afc-rate"))return;var key="afc-rating:"+p;var d={};try{d=JSON.parse(lc.getItem(key)||"{}")}catch(e){}var my=d.my||0;var box=document.createElement("div");box.id="afc-rate";box.style.cssText="margin:26px 0;padding:16px;border:1px solid #e6e8ee;border-radius:12px;text-align:center;font-family:system-ui,Arial";box.innerHTML='<div style="font-weight:700;margin-bottom:6px">Rate this tool</div><div id="afc-stars" style="font-size:26px;cursor:pointer;color:#f59e0b"></div><div id="afc-rmsg" style="color:#64748b;font-size:.85rem;margin-top:4px"></div>';m.appendChild(box);var stars=box.querySelector("#afc-stars"),msg=box.querySelector("#afc-rmsg");function render(){var h="";for(var i=1;i<=5;i++)h+='<span data-v="'+i+'">'+(i<=my?"\u2605":"\u2606")+"</span>";stars.innerHTML=h;}render();if(my)msg.textContent="You rated "+my+"/5. Thanks!";stars.addEventListener("click",function(e){var s=e.target.closest?e.target.closest("span"):null;if(!s)return;my=+s.getAttribute("data-v");d.my=my;try{lc.setItem(key,JSON.stringify(d))}catch(e){}render();msg.textContent="You rated "+my+"/5. Thanks!";});}
if(document.readyState!=="loading")draw();else document.addEventListener("DOMContentLoaded",draw);
})();