/* allfreecalculators.in - 200 additional working tools (groups A-H).
   Single source of truth: registers into CS.Calc + SEO in the browser,
   and exports {defs, meta, CMAP} under Node for the page generator/tests. */
(function (root) {
  'use strict';
  var isNode = (typeof module !== 'undefined' && module.exports);
  var pw = Math.pow, rt = Math.sqrt, ab = Math.abs, mx = Math.max, mn = Math.min, rnd = Math.round, fl = Math.floor, ce = Math.ceil, lg = Math.log, PI = Math.PI, DAY = 86400000;

  function nf(n, d) { d = d == null ? 2 : d; return isFinite(n) ? Number(n).toLocaleString('en-IN', { maximumFractionDigits: d }) : '\u2014'; }
  function money(n) { return isFinite(n) ? '\u20B9' + nf(n, 2) : '\u2014'; }
  function pct(n) { return isFinite(n) ? nf(n, 2) + '%' : '\u2014'; }
  function opt(v, l) { return { value: v, label: l }; }
  function LIST(s) { return String(s || '').split(/[^0-9.\-]+/).map(parseFloat).filter(function (x) { return isFinite(x); }); }
  function pdate(s) { var d = new Date(s); return isNaN(d.getTime()) ? null : d; }
  function fmtD(d) { return d ? d.toDateString() : '\u2014'; }
  function gcd(a, b) { a = ab(rnd(a)); b = ab(rnd(b)); while (b) { var t = b; b = a % b; a = t; } return a || 1; }
  function words(s) { s = String(s || '').trim(); return s ? s.split(/\s+/).length : 0; }
  function fact(n) { n = fl(n); if (n < 0) return NaN; var f = 1; for (var i = 2; i <= n; i++) f *= i; return f; }
  function roman(n) { var m = [[1000, 'M'], [900, 'CM'], [500, 'D'], [400, 'CD'], [100, 'C'], [90, 'XC'], [50, 'L'], [40, 'XL'], [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I']]; var s = ''; n = fl(n); if (n <= 0 || n > 3999) return '\u2014'; for (var i = 0; i < m.length; i++) { while (n >= m[i][0]) { s += m[i][1]; n -= m[i][0]; } } return s; }
  function slugify(s) { return String(s || '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || '\u2014'; }
  function hashN(s) { var x = 0; s = String(s); for (var i = 0; i < s.length; i++) x = (x * 31 + s.charCodeAt(i)) >>> 0; return x; }
  function uuid() { return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) { var r = Math.random() * 16 | 0; var v = c === 'x' ? r : (r & 0x3 | 0x8); return v.toString(16); }); }
  function emi(P, ratePa, nMon) { var i = ratePa / 1200; return i === 0 ? P / nMon : P * i * pw(1 + i, nMon) / (pw(1 + i, nMon) - 1); }
  function sentences(s) { var m = String(s || '').match(/[^.!?]+[.!?]+/g); return m ? m.length : (String(s || '').trim() ? 1 : 0); }
  var MORSE = { a: '.-', b: '-...', c: '-.-.', d: '-..', e: '.', f: '..-.', g: '--.', h: '....', i: '..', j: '.---', k: '-.-', l: '.-..', m: '--', n: '-.', o: '---', p: '.--.', q: '--.-', r: '.-.', s: '...', t: '-', u: '..-', v: '...-', w: '.--', x: '-..-', y: '-.--', z: '--..', '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....', '6': '-....', '7': '--...', '8': '---..', '9': '----.' };
  var MORSE_R = {}; for (var mk in MORSE) MORSE_R[MORSE[mk]] = mk;

  function simple(def) {
    return function () {
      var el = CS.el, wrap = el('div', { class: 'simplecalc' });
      var grid = el('div', { class: 'cs-grid' }), inputs = {};
      def.inputs.forEach(function (f) {
        var node;
        if (f.t === 'sel') node = CS.selectInput(f.opts, { value: f.v, onchange: run });
        else if (f.t === 'ta') { node = el('textarea', { rows: f.rows || 5, style: 'width:100%;min-height:110px' }); node.value = f.v != null ? f.v : ''; node.addEventListener('input', run); }
        else if (f.t === 'date' || f.t === 'time' || f.t === 'text') { node = el('input', { type: f.t, value: f.v != null ? f.v : '' }); node.addEventListener('input', run); node.addEventListener('change', run); }
        else node = CS.numInput({ value: f.v, step: f.step, oninput: run });
        inputs[f.k] = node;
        grid.appendChild(CS.field(f.label, node, f.hint));
      });
      var res = el('div', { class: 'result-area' });
      wrap.appendChild(grid); wrap.appendChild(res);
      function readv() { var o = {}; def.inputs.forEach(function (f) { var n = inputs[f.k]; o[f.k] = (f.t === 'sel' || f.t === 'date' || f.t === 'time' || f.t === 'text' || f.t === 'ta') ? n.value : parseFloat(n.value); }); return o; }
      function run() {
        var out; try { out = def.calc(readv()); } catch (e) { out = [['Error', 'Check your inputs']]; }
        res.innerHTML = ''; if (!out || !out.length) return;
        var row = el('div', { class: 'kpi-row' });
        out.forEach(function (p) { row.appendChild(CS.kpi(p[0], p[1], { class: p[2] || '' })); });
        res.appendChild(row);
      }
      setTimeout(run, 0); return wrap;
    };
  }

  var CMAP = {
    fin: { label: 'Financial', cslug: 'financial', folder: 'finance', icon: '\uD83D\uDCB0', suf: '-calculator' },
    tax: { label: 'Tax', cslug: 'financial', folder: 'tax', icon: '\uD83E\uDDFE', suf: '-calculator' },
    biz: { label: 'Business', cslug: 'business', folder: 'business', icon: '\uD83D\uDCBC', suf: '-calculator' },
    mkt: { label: 'Marketing', cslug: 'business', folder: 'business', icon: '\uD83D\uDCE3', suf: '-calculator' },
    seo: { label: 'SEO', cslug: 'seo-tools', folder: 'seo', icon: '\uD83D\uDD0E', suf: '-tool' },
    health: { label: 'Health', cslug: 'health', folder: 'health', icon: '\u2764\uFE0F', suf: '-calculator' },
    fit: { label: 'Fitness', cslug: 'health', folder: 'health', icon: '\uD83C\uDFC3', suf: '-calculator' },
    math: { label: 'Math', cslug: 'math', folder: 'math', icon: '\uD83E\uDDEE', suf: '-calculator' },
    stat: { label: 'Statistics', cslug: 'statistics', folder: 'math', icon: '\uD83D\uDCCA', suf: '-calculator' },
    geo: { label: 'Geometry', cslug: 'geometry', folder: 'math', icon: '\uD83D\uDCD0', suf: '-calculator' },
    every: { label: 'Everyday', cslug: 'everyday', folder: 'productivity', icon: '\uD83C\uDFE0', suf: '-calculator' },
    date: { label: 'Date & Time', cslug: 'datetime', folder: 'productivity', icon: '\uD83D\uDCC5', suf: '-calculator' },
    dev: { label: 'Developer', cslug: 'web-developer-tools', folder: 'utilities', icon: '\uD83D\uDCBB', suf: '-tool' },
    text: { label: 'Text', cslug: 'text-tools', folder: 'text', icon: '\uD83D\uDCDD', suf: '-tool' },
    conv: { label: 'Converters', cslug: 'conversions', folder: 'converters', icon: '\uD83D\uDD04', suf: '-converter' }
  };

  var defs = [];
  function T(id, name, cat, kw, blurb, def) { defs.push({ id: id, name: name, cat: cat, kw: kw, blurb: blurb, def: def }); }

  /* ===== GROUP A: Finance / Tax (30) ===== */
  T('nps-corpus', 'NPS Corpus Calculator', 'fin', 'nps corpus calculator, national pension scheme', 'Estimate your NPS retirement corpus, annuity and lump sum.', { inputs: [{ k: 'p', label: 'Monthly contribution', v: 5000, step: 'any' }, { k: 'r', label: 'Expected return (% p.a.)', v: 10, step: 'any' }, { k: 'y', label: 'Years to retirement', v: 30, step: 1 }], calc: function (v) { var i = v.r / 1200, m = v.y * 12; var fv = v.p * ((pw(1 + i, m) - 1) / i) * (1 + i); return [['Total corpus', money(fv)], ['Min annuity (40%)', money(fv * 0.4)], ['Lump sum (60%)', money(fv * 0.6)]]; } });
  T('epf-corpus', 'EPF Corpus Calculator', 'fin', 'epf corpus calculator, provident fund maturity', 'Estimate your EPF maturity corpus at retirement.', { inputs: [{ k: 'b', label: 'Monthly Basic + DA', v: 25000, step: 'any' }, { k: 'r', label: 'Interest rate (% p.a.)', v: 8.15, step: 'any' }, { k: 'y', label: 'Years of service', v: 30, step: 1 }], calc: function (v) { var c = v.b * 0.24, i = v.r / 1200, m = v.y * 12; var fv = c * ((pw(1 + i, m) - 1) / i) * (1 + i); return [['EPF corpus', money(fv)], ['Total invested', money(c * m)], ['Interest', money(fv - c * m)]]; } });
  T('sukanya-samriddhi', 'Sukanya Samriddhi Yojana Calculator', 'fin', 'sukanya samriddhi calculator, ssy maturity', 'Estimate SSY maturity value from yearly deposits.', { inputs: [{ k: 'p', label: 'Yearly deposit', v: 150000, step: 'any' }, { k: 'r', label: 'Interest rate (%)', v: 8, step: 'any' }], calc: function (v) { var i = v.r / 100, fv = 0; for (var y = 1; y <= 15; y++) fv = (fv + v.p) * (1 + i); for (var z = 16; z <= 21; z++) fv = fv * (1 + i); return [['Maturity value', money(fv)], ['Total deposited', money(v.p * 15)], ['Interest', money(fv - v.p * 15)]]; } });
  T('post-office-mis', 'Post Office MIS Calculator', 'fin', 'post office mis calculator, monthly income scheme', 'Find monthly income from the Post Office MIS scheme.', { inputs: [{ k: 'p', label: 'Investment amount', v: 900000, step: 'any' }, { k: 'r', label: 'Interest rate (% p.a.)', v: 7.4, step: 'any' }], calc: function (v) { var mi = v.p * v.r / 1200; return [['Monthly income', money(mi)], ['Yearly income', money(mi * 12)], ['Over 5 years', money(mi * 60)]]; } });
  T('swp', 'SWP Calculator', 'fin', 'swp calculator, systematic withdrawal plan', 'See how long your corpus lasts with monthly withdrawals.', { inputs: [{ k: 'c', label: 'Total corpus', v: 1000000, step: 'any' }, { k: 'w', label: 'Monthly withdrawal', v: 10000, step: 'any' }, { k: 'r', label: 'Expected return (% p.a.)', v: 8, step: 'any' }], calc: function (v) { var i = v.r / 1200; if (v.w <= v.c * i) return [['Duration', 'Corpus never depletes'], ['Monthly interest', money(v.c * i)]]; var n = lg(v.w / (v.w - v.c * i)) / lg(1 + i); return [['Lasts (months)', nf(n, 0)], ['Lasts (years)', nf(n / 12, 1)]]; } });
  T('cagr', 'CAGR Calculator', 'fin', 'cagr calculator, compound annual growth rate', 'Calculate the compound annual growth rate of an investment.', { inputs: [{ k: 'b', label: 'Initial value', v: 10000, step: 'any' }, { k: 'e', label: 'Final value', v: 20000, step: 'any' }, { k: 'y', label: 'Years', v: 5, step: 'any' }], calc: function (v) { var c = (pw(v.e / v.b, 1 / v.y) - 1) * 100; return [['CAGR', pct(c)], ['Total growth', pct((v.e / v.b - 1) * 100)]]; } });
  T('lumpsum-investment', 'Lumpsum Investment Calculator', 'fin', 'lumpsum calculator, lumpsum investment return', 'Project the future value of a one-time investment.', { inputs: [{ k: 'p', label: 'Investment amount', v: 100000, step: 'any' }, { k: 'r', label: 'Expected return (% p.a.)', v: 12, step: 'any' }, { k: 'y', label: 'Years', v: 10, step: 'any' }], calc: function (v) { var fv = v.p * pw(1 + v.r / 100, v.y); return [['Future value', money(fv)], ['Gain', money(fv - v.p)]]; } });
  T('step-up-sip', 'Step Up SIP Calculator', 'fin', 'step up sip calculator, top up sip', 'Project SIP growth when you increase the amount yearly.', { inputs: [{ k: 'p', label: 'Monthly SIP', v: 5000, step: 'any' }, { k: 'r', label: 'Return (% p.a.)', v: 12, step: 'any' }, { k: 'y', label: 'Years', v: 10, step: 1 }, { k: 's', label: 'Yearly step-up (%)', v: 10, step: 'any' }], calc: function (v) { var i = v.r / 1200, fv = 0, inv = 0; for (var k = 0; k < v.y; k++) { var amt = v.p * pw(1 + v.s / 100, k); for (var mo = 0; mo < 12; mo++) { fv = (fv + amt) * (1 + i); inv += amt; } } return [['Corpus', money(fv)], ['Invested', money(inv)], ['Gain', money(fv - inv)]]; } });
  T('loan-prepayment', 'Loan Prepayment Calculator', 'fin', 'loan prepayment calculator, part payment savings', 'See interest saved by making a lump-sum loan prepayment.', { inputs: [{ k: 'p', label: 'Loan amount', v: 1000000, step: 'any' }, { k: 'r', label: 'Interest rate (% p.a.)', v: 9, step: 'any' }, { k: 'n', label: 'Tenure (months)', v: 240, step: 1 }, { k: 'pre', label: 'Prepayment amount', v: 200000, step: 'any' }], calc: function (v) { var i = v.r / 1200, e = emi(v.p, v.r, v.n), origInt = e * v.n - v.p, np = v.p - v.pre; var nn = lg(e / (e - np * i)) / lg(1 + i); var newInt = e * nn - np; return [['EMI', money(e)], ['Interest saved', money(origInt - newInt)], ['New tenure (months)', nf(nn, 0)]]; } });
  T('balloon-loan', 'Balloon Loan Calculator', 'fin', 'balloon loan calculator, balloon payment', 'Calculate EMI for a loan with a final balloon payment.', { inputs: [{ k: 'p', label: 'Loan amount', v: 1000000, step: 'any' }, { k: 'r', label: 'Interest rate (% p.a.)', v: 9, step: 'any' }, { k: 'n', label: 'Term (months)', v: 60, step: 1 }, { k: 'bl', label: 'Balloon payment', v: 300000, step: 'any' }], calc: function (v) { var i = v.r / 1200; var e = (v.p - v.bl / pw(1 + i, v.n)) * i / (1 - pw(1 + i, -v.n)); return [['Monthly EMI', money(e)], ['Balloon due at end', money(v.bl)]]; } });
  T('mortgage-refinance', 'Mortgage Refinance Calculator', 'fin', 'mortgage refinance calculator, refinance savings', 'Compare your current and refinanced home loan EMI.', { inputs: [{ k: 'p', label: 'Outstanding balance', v: 2000000, step: 'any' }, { k: 'o', label: 'Current rate (%)', v: 9, step: 'any' }, { k: 'nr', label: 'New rate (%)', v: 8, step: 'any' }, { k: 'n', label: 'Remaining months', v: 180, step: 1 }], calc: function (v) { var e1 = emi(v.p, v.o, v.n), e2 = emi(v.p, v.nr, v.n); return [['Current EMI', money(e1)], ['New EMI', money(e2)], ['Monthly saving', money(e1 - e2)], ['Total saving', money((e1 - e2) * v.n)]]; } });
  T('car-loan-emi', 'Car Loan EMI Calculator', 'fin', 'car loan emi calculator, auto loan emi', 'Calculate the EMI for a car loan after down payment.', { inputs: [{ k: 'price', label: 'Car price', v: 800000, step: 'any' }, { k: 'dp', label: 'Down payment', v: 100000, step: 'any' }, { k: 'r', label: 'Interest rate (% p.a.)', v: 9, step: 'any' }, { k: 'n', label: 'Tenure (months)', v: 60, step: 1 }], calc: function (v) { var P = v.price - v.dp, e = emi(P, v.r, v.n); return [['Monthly EMI', money(e)], ['Loan amount', money(P)], ['Total interest', money(e * v.n - P)]]; } });
  T('education-loan-emi', 'Education Loan EMI Calculator', 'fin', 'education loan emi calculator, student loan emi', 'Calculate EMI and total payment for an education loan.', { inputs: [{ k: 'p', label: 'Loan amount', v: 1000000, step: 'any' }, { k: 'r', label: 'Interest rate (% p.a.)', v: 10, step: 'any' }, { k: 'n', label: 'Tenure (months)', v: 84, step: 1 }], calc: function (v) { var e = emi(v.p, v.r, v.n); return [['Monthly EMI', money(e)], ['Total payment', money(e * v.n)], ['Total interest', money(e * v.n - v.p)]]; } });
  T('gold-loan', 'Gold Loan Eligibility Calculator', 'fin', 'gold loan calculator, gold loan eligibility', 'Estimate the loan you can get against your gold.', { inputs: [{ k: 'g', label: 'Gold weight (grams)', v: 50, step: 'any' }, { k: 'rate', label: 'Rate per gram', v: 6000, step: 'any' }, { k: 'ltv', label: 'LTV (%)', v: 75, step: 'any' }], calc: function (v) { var val = v.g * v.rate; return [['Gold value', money(val)], ['Eligible loan', money(val * v.ltv / 100)]]; } });
  T('ltcg-tax', 'LTCG Tax Calculator', 'tax', 'ltcg tax calculator, long term capital gains tax', 'Estimate long-term capital gains tax on equity (12.5%).', { inputs: [{ k: 'buy', label: 'Buy value', v: 100000, step: 'any' }, { k: 'sell', label: 'Sell value', v: 300000, step: 'any' }], calc: function (v) { var g = v.sell - v.buy, tx = mx(0, g - 125000); return [['Capital gain', money(g)], ['Taxable gain', money(tx)], ['Tax (12.5%)', money(tx * 0.125)]]; } });
  T('stcg-tax', 'STCG Tax Calculator', 'tax', 'stcg tax calculator, short term capital gains tax', 'Estimate short-term capital gains tax on equity (20%).', { inputs: [{ k: 'g', label: 'Short-term gain', v: 50000, step: 'any' }], calc: function (v) { return [['Tax (20%)', money(v.g * 0.20)], ['Net gain', money(v.g * 0.80)]]; } });
  T('tds-interest', 'TDS on Interest Calculator', 'tax', 'tds calculator, tds on interest', 'Calculate TDS deducted on interest income (10%).', { inputs: [{ k: 'i', label: 'Interest income', v: 60000, step: 'any' }, { k: 'r', label: 'TDS rate (%)', v: 10, step: 'any' }], calc: function (v) { var t = v.i * v.r / 100; return [['TDS', money(t)], ['Net received', money(v.i - t)]]; } });
  T('advance-tax', 'Advance Tax Installment Calculator', 'tax', 'advance tax calculator, advance tax installments', 'Split your annual tax into advance tax installments.', { inputs: [{ k: 't', label: 'Total tax payable', v: 100000, step: 'any' }], calc: function (v) { return [['By 15 Jun (15%)', money(v.t * 0.15)], ['By 15 Sep (45%)', money(v.t * 0.45)], ['By 15 Dec (75%)', money(v.t * 0.75)], ['By 15 Mar (100%)', money(v.t)]]; } });
  T('professional-tax', 'Professional Tax Calculator', 'tax', 'professional tax calculator, pt deduction', 'Estimate monthly professional tax from your salary.', { inputs: [{ k: 's', label: 'Monthly salary', v: 25000, step: 'any' }], calc: function (v) { var pt = v.s >= 15000 ? 200 : (v.s >= 10000 ? 175 : 0); return [['Monthly PT', money(pt)], ['Yearly PT', money(pt * 12)]]; } });
  T('salary-inhand', 'In-Hand Salary Calculator', 'tax', 'in hand salary calculator, take home salary', 'Estimate your monthly take-home salary from CTC.', { inputs: [{ k: 'ctc', label: 'Annual CTC', v: 1200000, step: 'any' }], calc: function (v) { var basic = 0.4 * v.ctc, epf = 0.12 * basic, emprPF = 0.12 * basic, grat = 0.0481 * basic; var net = v.ctc - emprPF - grat - epf - 2400; return [['Monthly in-hand (approx)', money(net / 12)], ['Yearly in-hand (approx)', money(net)]]; } });
  T('ctc-breakup', 'CTC Breakup Calculator', 'tax', 'ctc breakup calculator, salary structure', 'Break your CTC into basic, HRA, PF and allowances.', { inputs: [{ k: 'ctc', label: 'Annual CTC', v: 1200000, step: 'any' }], calc: function (v) { var basic = 0.4 * v.ctc, hra = 0.5 * basic, pf = 0.12 * basic; return [['Basic (40%)', money(basic)], ['HRA', money(hra)], ['Employer PF', money(pf)], ['Special allowance', money(v.ctc - basic - hra - pf)]]; } });
  T('gst-late-fee', 'GST Late Fee Calculator', 'tax', 'gst late fee calculator, gstr late fee', 'Estimate the late fee for delayed GST return filing.', { inputs: [{ k: 'd', label: 'Days late', v: 10, step: 1 }], calc: function (v) { var fee = mn(v.d * 50, 5000); return [['Late fee (CGST+SGST)', money(fee)], ['Per day', money(50)]]; } });
  T('tcs-tax', 'TCS Calculator', 'tax', 'tcs calculator, tax collected at source', 'Calculate tax collected at source on a sale amount.', { inputs: [{ k: 'a', label: 'Amount', v: 1000000, step: 'any' }, { k: 'r', label: 'TCS rate (%)', v: 0.1, step: 'any' }], calc: function (v) { var t = v.a * v.r / 100; return [['TCS', money(t)], ['Total collected', money(v.a + t)]]; } });
  T('dividend-tax', 'Dividend Tax Calculator', 'tax', 'dividend tax calculator, tax on dividend', 'Estimate tax payable on dividend income by slab.', { inputs: [{ k: 'd', label: 'Dividend income', v: 50000, step: 'any' }, { k: 's', label: 'Your slab (%)', v: 30, step: 'any' }], calc: function (v) { var t = v.d * v.s / 100; return [['Tax', money(t)], ['Net dividend', money(v.d - t)]]; } });
  T('retirement-corpus', 'Retirement Corpus Calculator', 'fin', 'retirement corpus calculator, retirement planning', 'Find the corpus needed to fund your retirement.', { inputs: [{ k: 'e', label: 'Monthly expense (today)', v: 50000, step: 'any' }, { k: 'y', label: 'Years to retirement', v: 20, step: 1 }, { k: 'inf', label: 'Inflation (%)', v: 6, step: 'any' }, { k: 'wr', label: 'Withdrawal rate (%)', v: 4, step: 'any' }], calc: function (v) { var futAnnual = v.e * 12 * pw(1 + v.inf / 100, v.y); return [['Future annual expense', money(futAnnual)], ['Corpus needed', money(futAnnual / (v.wr / 100))]]; } });
  T('inflation-adjusted', 'Inflation Calculator', 'fin', 'inflation calculator, future value of money', 'See the future cost and real value of money with inflation.', { inputs: [{ k: 'a', label: 'Amount today', v: 100000, step: 'any' }, { k: 'inf', label: 'Inflation (%)', v: 6, step: 'any' }, { k: 'y', label: 'Years', v: 10, step: 'any' }], calc: function (v) { var f = v.a * pw(1 + v.inf / 100, v.y); return [['Future cost', money(f)], ['Real value of today amount', money(v.a / pw(1 + v.inf / 100, v.y))]]; } });
  T('emergency-fund', 'Emergency Fund Calculator', 'fin', 'emergency fund calculator, emergency savings', 'Find how big your emergency fund should be.', { inputs: [{ k: 'e', label: 'Monthly expenses', v: 40000, step: 'any' }, { k: 'm', label: 'Months of cover', v: 6, step: 1 }], calc: function (v) { return [['Emergency fund', money(v.e * v.m)]]; } });
  T('sip-goal', 'SIP Goal Calculator', 'fin', 'sip goal calculator, required sip amount', 'Find the monthly SIP needed to reach a target amount.', { inputs: [{ k: 't', label: 'Target amount', v: 1000000, step: 'any' }, { k: 'y', label: 'Years', v: 5, step: 1 }, { k: 'r', label: 'Return (% p.a.)', v: 12, step: 'any' }], calc: function (v) { var i = v.r / 1200, m = v.y * 12; var sip = v.t * i / ((pw(1 + i, m) - 1) * (1 + i)); return [['Required monthly SIP', money(sip)], ['Total invested', money(sip * m)]]; } });

  /* ===== GROUP B: Health / Fitness (25) ===== */
  T('macro', 'Macro Calculator', 'health', 'macro calculator, macronutrient split', 'Split your daily calories into protein, carbs and fat.', { inputs: [{ k: 'cal', label: 'Daily calories', v: 2000, step: 'any' }, { k: 'pp', label: 'Protein (%)', v: 30, step: 'any' }, { k: 'cp', label: 'Carbs (%)', v: 40, step: 'any' }, { k: 'fp', label: 'Fat (%)', v: 30, step: 'any' }], calc: function (v) { return [['Protein', nf(v.cal * v.pp / 100 / 4, 0) + ' g'], ['Carbs', nf(v.cal * v.cp / 100 / 4, 0) + ' g'], ['Fat', nf(v.cal * v.fp / 100 / 9, 0) + ' g']]; } });
  T('protein-intake', 'Protein Intake Calculator', 'health', 'protein intake calculator, daily protein needs', 'Find how much protein you should eat per day.', { inputs: [{ k: 'w', label: 'Body weight (kg)', v: 70, step: 'any' }, { k: 'a', label: 'Activity', t: 'sel', v: '1.2', opts: [opt('0.8', 'Sedentary'), opt('1.2', 'Active'), opt('1.6', 'Strength training'), opt('2', 'Athlete')] }], calc: function (v) { return [['Protein per day', nf(v.w * parseFloat(v.a), 0) + ' g']]; } });
  T('tdee', 'TDEE Calculator', 'health', 'tdee calculator, total daily energy expenditure', 'Estimate your total daily energy expenditure.', { inputs: [{ k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }, { k: 'h', label: 'Height (cm)', v: 175, step: 'any' }, { k: 'age', label: 'Age', v: 30, step: 1 }, { k: 'g', label: 'Gender', t: 'sel', v: 'm', opts: [opt('m', 'Male'), opt('f', 'Female')] }, { k: 'a', label: 'Activity', t: 'sel', v: '1.55', opts: [opt('1.2', 'Sedentary'), opt('1.375', 'Light'), opt('1.55', 'Moderate'), opt('1.725', 'Very active')] }], calc: function (v) { var bmr = 10 * v.w + 6.25 * v.h - 5 * v.age + (v.g === 'm' ? 5 : -161); return [['BMR', nf(bmr, 0) + ' kcal'], ['TDEE', nf(bmr * parseFloat(v.a), 0) + ' kcal']]; } });
  T('one-rep-max', 'One Rep Max Calculator', 'fit', 'one rep max calculator, 1rm calculator', 'Estimate your one-rep max from weight and reps.', { inputs: [{ k: 'w', label: 'Weight lifted (kg)', v: 60, step: 'any' }, { k: 'reps', label: 'Reps', v: 8, step: 1 }], calc: function (v) { var orm = v.w * (1 + v.reps / 30); return [['Estimated 1RM', nf(orm, 1) + ' kg'], ['85% of 1RM', nf(orm * 0.85, 1) + ' kg']]; } });
  T('heart-rate-zone', 'Heart Rate Zone Calculator', 'fit', 'heart rate zone calculator, target heart rate', 'Find your training heart rate zones from your age.', { inputs: [{ k: 'age', label: 'Age', v: 30, step: 1 }], calc: function (v) { var mhr = 220 - v.age; return [['Max heart rate', nf(mhr, 0) + ' bpm'], ['Fat burn (60-70%)', nf(mhr * 0.6, 0) + '-' + nf(mhr * 0.7, 0)], ['Cardio (70-85%)', nf(mhr * 0.7, 0) + '-' + nf(mhr * 0.85, 0)]]; } });
  T('vo2-max', 'VO2 Max Calculator', 'fit', 'vo2 max calculator, cooper test', 'Estimate VO2 max from a 12-minute Cooper run.', { inputs: [{ k: 'd', label: 'Distance in 12 min (m)', v: 2400, step: 'any' }], calc: function (v) { return [['VO2 max', nf((v.d - 504.9) / 44.73, 1) + ' ml/kg/min']]; } });
  T('waist-hip-ratio', 'Waist to Hip Ratio Calculator', 'health', 'waist to hip ratio calculator, whr', 'Calculate your waist-to-hip ratio and health category.', { inputs: [{ k: 'w', label: 'Waist (cm)', v: 80, step: 'any' }, { k: 'h', label: 'Hip (cm)', v: 100, step: 'any' }], calc: function (v) { var r = v.w / v.h; return [['Ratio', nf(r, 2)], ['Category', r < 0.9 ? 'Low risk' : (r < 1 ? 'Moderate' : 'High risk')]]; } });
  T('lean-body-mass', 'Lean Body Mass Calculator', 'health', 'lean body mass calculator, lbm', 'Estimate lean body mass from weight and body fat.', { inputs: [{ k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }, { k: 'bf', label: 'Body fat (%)', v: 20, step: 'any' }], calc: function (v) { return [['Lean body mass', nf(v.w * (1 - v.bf / 100), 1) + ' kg'], ['Fat mass', nf(v.w * v.bf / 100, 1) + ' kg']]; } });
  T('calorie-deficit', 'Calorie Deficit Calculator', 'fit', 'calorie deficit calculator, weight loss calories', 'Find your daily intake and weekly loss from a deficit.', { inputs: [{ k: 't', label: 'TDEE (kcal)', v: 2200, step: 'any' }, { k: 'd', label: 'Daily deficit (kcal)', v: 500, step: 'any' }], calc: function (v) { return [['Daily intake', nf(v.t - v.d, 0) + ' kcal'], ['Weekly fat loss', nf(v.d * 7 / 7700, 2) + ' kg']]; } });
  T('ovulation', 'Ovulation Calculator', 'health', 'ovulation calculator, fertile window', 'Estimate your ovulation date and fertile window.', { inputs: [{ k: 'lmp', label: 'Last period start', t: 'date', v: '' }, { k: 'cyc', label: 'Cycle length (days)', v: 28, step: 1 }], calc: function (v) { var d = pdate(v.lmp); if (!d) return [['Ovulation', 'Enter a date']]; var ov = new Date(d.getTime() + (v.cyc - 14) * DAY); return [['Ovulation date', fmtD(ov)], ['Fertile window', fmtD(new Date(ov.getTime() - 3 * DAY)) + ' to ' + fmtD(new Date(ov.getTime() + DAY))]]; } });
  T('pregnancy-week', 'Pregnancy Week Calculator', 'health', 'pregnancy week calculator, how many weeks pregnant', 'Find how many weeks pregnant you are from the LMP.', { inputs: [{ k: 'lmp', label: 'Last menstrual period', t: 'date', v: '' }], calc: function (v) { var d = pdate(v.lmp); if (!d) return [['Weeks', 'Enter a date']]; var wk = fl((Date.now() - d.getTime()) / (7 * DAY)); return [['Weeks pregnant', wk + ' weeks'], ['Trimester', wk < 13 ? 'First' : (wk < 27 ? 'Second' : 'Third')]]; } });
  T('sleep-cycle', 'Sleep Cycle Calculator', 'health', 'sleep cycle calculator, best time to sleep', 'Find the best bedtimes based on 90-minute sleep cycles.', { inputs: [{ k: 'wake', label: 'Wake-up time', t: 'time', v: '06:30' }], calc: function (v) { if (!v.wake) return [['Bedtime', 'Enter a time']]; var p = v.wake.split(':'); var w = parseInt(p[0], 10) * 60 + parseInt(p[1], 10); function t(mins) { mins = ((mins % 1440) + 1440) % 1440; var h = fl(mins / 60), m = mins % 60; return (h < 10 ? '0' : '') + h + ':' + (m < 10 ? '0' : '') + m; } return [['6 cycles', t(w - 14 - 540)], ['5 cycles', t(w - 14 - 450)], ['4 cycles', t(w - 14 - 360)]]; } });
  T('blood-alcohol', 'Blood Alcohol Calculator', 'health', 'blood alcohol calculator, bac calculator', 'Estimate blood alcohol content using the Widmark formula.', { inputs: [{ k: 'drinks', label: 'Standard drinks', v: 2, step: 'any' }, { k: 'w', label: 'Body weight (kg)', v: 70, step: 'any' }, { k: 'g', label: 'Gender', t: 'sel', v: '0.68', opts: [opt('0.68', 'Male'), opt('0.55', 'Female')] }, { k: 'hrs', label: 'Hours since first drink', v: 1, step: 'any' }], calc: function (v) { var grams = v.drinks * 14; var bac = (grams / (v.w * 1000 * parseFloat(v.g))) * 100 - 0.015 * v.hrs; return [['Estimated BAC', pct(mx(0, bac))], ['Legal limit (India)', '0.03%']]; } });
  T('smoking-cost', 'Smoking Cost Calculator', 'health', 'smoking cost calculator, cost of smoking', 'See how much your smoking habit costs over time.', { inputs: [{ k: 'cpd', label: 'Cigarettes per day', v: 10, step: 1 }, { k: 'pack', label: 'Cigarettes per pack', v: 20, step: 1 }, { k: 'price', label: 'Price per pack', v: 300, step: 'any' }, { k: 'y', label: 'Years', v: 10, step: 1 }], calc: function (v) { var daily = v.cpd / v.pack * v.price; return [['Daily cost', money(daily)], ['Yearly cost', money(daily * 365)], ['Over ' + v.y + ' years', money(daily * 365 * v.y)]]; } });
  T('steps-to-calories', 'Steps to Calories Calculator', 'fit', 'steps to calories calculator, calories from steps', 'Estimate calories burned from your step count.', { inputs: [{ k: 'steps', label: 'Steps', v: 8000, step: 1 }, { k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }], calc: function (v) { var cal = v.steps * 0.04 * (v.w / 70); return [['Calories burned', nf(cal, 0) + ' kcal'], ['Distance (approx)', nf(v.steps * 0.0008, 2) + ' km']]; } });
  T('cycling-calories', 'Cycling Calories Calculator', 'fit', 'cycling calories calculator, calories cycling', 'Estimate calories burned while cycling.', { inputs: [{ k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }, { k: 'min', label: 'Duration (minutes)', v: 30, step: 1 }, { k: 'met', label: 'Intensity', t: 'sel', v: '8', opts: [opt('4', 'Leisure'), opt('8', 'Moderate'), opt('10', 'Vigorous'), opt('12', 'Racing')] }], calc: function (v) { return [['Calories burned', nf(parseFloat(v.met) * 3.5 * v.w / 200 * v.min, 0) + ' kcal']]; } });
  T('running-pace', 'Running Pace Calculator', 'fit', 'running pace calculator, pace per km', 'Calculate your running pace and speed.', { inputs: [{ k: 'd', label: 'Distance (km)', v: 5, step: 'any' }, { k: 't', label: 'Time (minutes)', v: 30, step: 'any' }], calc: function (v) { var pace = v.t / v.d; return [['Pace', nf(fl(pace), 0) + ':' + (rnd((pace % 1) * 60) < 10 ? '0' : '') + rnd((pace % 1) * 60) + ' /km'], ['Speed', nf(v.d / (v.t / 60), 2) + ' km/h']]; } });
  T('marathon-time', 'Marathon Time Calculator', 'fit', 'marathon time calculator, finish time predictor', 'Predict marathon and half-marathon finish times from pace.', { inputs: [{ k: 'pace', label: 'Pace (min/km)', v: 6, step: 'any' }], calc: function (v) { function hms(min) { var h = fl(min / 60), m = fl(min % 60); return h + 'h ' + m + 'm'; } return [['Marathon (42.2 km)', hms(42.195 * v.pace)], ['Half marathon', hms(21.0975 * v.pace)], ['10K', hms(10 * v.pace)]]; } });
  T('swim-pace', 'Swim Pace Calculator', 'fit', 'swim pace calculator, pace per 100m', 'Calculate your swimming pace per 100 metres.', { inputs: [{ k: 'd', label: 'Distance (m)', v: 1000, step: 'any' }, { k: 't', label: 'Time (minutes)', v: 20, step: 'any' }], calc: function (v) { var pace = v.t / (v.d / 100); return [['Pace per 100m', nf(fl(pace), 0) + ':' + (rnd((pace % 1) * 60) < 10 ? '0' : '') + rnd((pace % 1) * 60)], ['Speed', nf(v.d / v.t, 1) + ' m/min']]; } });
  T('hydration-athlete', 'Athlete Hydration Calculator', 'fit', 'hydration calculator, water intake athlete', 'Estimate daily water needs including exercise.', { inputs: [{ k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }, { k: 'min', label: 'Exercise (minutes)', v: 60, step: 1 }], calc: function (v) { var l = v.w * 0.033 + v.min / 60 * 0.5; return [['Water per day', nf(l, 2) + ' L'], ['Glasses (250ml)', nf(l * 1000 / 250, 0)]]; } });
  T('body-surface-area', 'Body Surface Area Calculator', 'health', 'body surface area calculator, bsa mosteller', 'Estimate body surface area using the Mosteller formula.', { inputs: [{ k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }, { k: 'h', label: 'Height (cm)', v: 175, step: 'any' }], calc: function (v) { return [['Body surface area', nf(rt(v.w * v.h / 3600), 2) + ' m\u00B2']]; } });
  T('dog-age', 'Dog Age Calculator', 'health', 'dog age calculator, dog years to human years', 'Convert your dog\u2019s age into human years.', { inputs: [{ k: 'y', label: 'Dog age (years)', v: 3, step: 'any' }], calc: function (v) { var human = v.y <= 0 ? 0 : 16 * lg(v.y) / lg(Math.E) + 31; return [['Human-equivalent age', nf(human, 0) + ' years']]; } });
  T('weight-loss-calories', 'Weight Loss Calorie Calculator', 'fit', 'weight loss calorie calculator, calories to lose weight', 'Find the daily deficit to reach a target weight.', { inputs: [{ k: 'cur', label: 'Current weight (kg)', v: 80, step: 'any' }, { k: 'tgt', label: 'Target weight (kg)', v: 70, step: 'any' }, { k: 'wks', label: 'Weeks', v: 10, step: 1 }], calc: function (v) { var kg = v.cur - v.tgt; return [['Total fat to lose', nf(kg, 1) + ' kg'], ['Daily deficit needed', nf(kg * 7700 / (v.wks * 7), 0) + ' kcal']]; } });
  T('max-fat-burn-hr', 'Fat Burning Heart Rate Calculator', 'fit', 'fat burning heart rate calculator', 'Find your optimal fat-burning heart rate.', { inputs: [{ k: 'age', label: 'Age', v: 30, step: 1 }], calc: function (v) { return [['Target HR (fat burn)', nf(0.7 * (220 - v.age), 0) + ' bpm'], ['Zone', nf(0.6 * (220 - v.age), 0) + '-' + nf(0.7 * (220 - v.age), 0) + ' bpm']]; } });
  T('waist-height-ratio', 'Waist to Height Ratio Calculator', 'health', 'waist to height ratio calculator', 'Calculate your waist-to-height ratio and risk level.', { inputs: [{ k: 'w', label: 'Waist (cm)', v: 80, step: 'any' }, { k: 'h', label: 'Height (cm)', v: 175, step: 'any' }], calc: function (v) { var r = v.w / v.h; return [['Ratio', nf(r, 2)], ['Assessment', r < 0.5 ? 'Healthy' : (r < 0.6 ? 'Increased risk' : 'High risk')]]; } });

  /*__TOOLS__*/

  var metaArr = defs.map(function (d) { var c = CMAP[d.cat] || CMAP.math; return { id: d.id, name: d.name, cat: d.cat, label: c.label, kw: d.kw, blurb: d.blurb, slug: d.id + c.suf, folder: c.folder, cslug: c.cslug, icon: c.icon }; });
  if (isNode) { module.exports = { defs: defs, meta: metaArr, CMAP: CMAP }; return; }
  var CS = root.CS, SEO = root.SEO;
  if (!CS || !CS.Calc) return;
  defs.forEach(function (d) { var c = CMAP[d.cat] || CMAP.math; CS.Calc.register({ id: d.id, name: d.name, category: c.label, icon: c.icon, description: d.blurb, render: simple(d.def) }); });
  if (SEO && SEO.TOOLS) { defs.forEach(function (d) { var c = CMAP[d.cat] || CMAP.math; var slug = d.id + c.suf; if (!SEO.TOOLS[d.id]) { SEO.TOOLS[d.id] = { slug: slug, cat: c.cslug, icon: c.icon, name: d.name, title: d.name + ' | allfreecalculators.in', desc: d.blurb, keywords: d.kw, intro: d.blurb, options: [], faqs: [{ q: 'Is the ' + d.name + ' free?', a: 'Yes, it is 100% free with no sign-up.' }, { q: 'Does it work on mobile?', a: 'Yes, it runs in your browser on any device.' }], related: [] }; if (SEO.ORDER && SEO.ORDER.indexOf(d.id) < 0) SEO.ORDER.push(d.id); } }); }
})(typeof self !== 'undefined' ? self : this);
