/* allfreecalculators.in - group C (Math / Statistics / Geometry, 30). Self-contained. */
(function (root) {
  'use strict';
  var isNode = (typeof module !== 'undefined' && module.exports);
  var pw = Math.pow, rt = Math.sqrt, ab = Math.abs, mx = Math.max, mn = Math.min, rnd = Math.round, fl = Math.floor, lg = Math.log, PI = Math.PI, atan2 = Math.atan2;
  function nf(n, d) { d = d == null ? 2 : d; return isFinite(n) ? Number(n).toLocaleString('en-IN', { maximumFractionDigits: d }) : '\u2014'; }
  function pct(n) { return isFinite(n) ? nf(n, 2) + '%' : '\u2014'; }
  function opt(v, l) { return { value: v, label: l }; }
  function LIST(s) { return String(s || '').split(/[^0-9.\-]+/).map(parseFloat).filter(function (x) { return isFinite(x); }); }
  function gcd(a, b) { a = ab(rnd(a)); b = ab(rnd(b)); while (b) { var t = b; b = a % b; a = t; } return a || 1; }
  function fact(n) { n = fl(n); if (n < 0) return NaN; var f = 1; for (var i = 2; i <= n; i++) f *= i; return f; }
  function roman(n) { var m = [[1000, 'M'], [900, 'CM'], [500, 'D'], [400, 'CD'], [100, 'C'], [90, 'XC'], [50, 'L'], [40, 'XL'], [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I']]; var s = ''; n = fl(n); if (n <= 0 || n > 3999) return '\u2014'; for (var i = 0; i < m.length; i++) { while (n >= m[i][0]) { s += m[i][1]; n -= m[i][0]; } } return s; }
  function simple(def) { return function () { var el = CS.el, wrap = el('div', { class: 'simplecalc' }); var grid = el('div', { class: 'cs-grid' }), inputs = {}; def.inputs.forEach(function (f) { var node; if (f.t === 'sel') node = CS.selectInput(f.opts, { value: f.v, onchange: run }); else if (f.t === 'ta') { node = el('textarea', { rows: f.rows || 5, style: 'width:100%;min-height:110px' }); node.value = f.v != null ? f.v : ''; node.addEventListener('input', run); } else if (f.t === 'date' || f.t === 'time' || f.t === 'text') { node = el('input', { type: f.t, value: f.v != null ? f.v : '' }); node.addEventListener('input', run); node.addEventListener('change', run); } else node = CS.numInput({ value: f.v, step: f.step, oninput: run }); inputs[f.k] = node; grid.appendChild(CS.field(f.label, node, f.hint)); }); var res = el('div', { class: 'result-area' }); wrap.appendChild(grid); wrap.appendChild(res); function readv() { var o = {}; def.inputs.forEach(function (f) { var n = inputs[f.k]; o[f.k] = (f.t === 'sel' || f.t === 'date' || f.t === 'time' || f.t === 'text' || f.t === 'ta') ? n.value : parseFloat(n.value); }); return o; } function run() { var out; try { out = def.calc(readv()); } catch (e) { out = [['Error', 'Check your inputs']]; } res.innerHTML = ''; if (!out || !out.length) return; var row = el('div', { class: 'kpi-row' }); out.forEach(function (p) { row.appendChild(CS.kpi(p[0], p[1], { class: p[2] || '' })); }); res.appendChild(row); } setTimeout(run, 0); return wrap; }; }
  var CMAP = { math: { label: 'Math', cslug: 'math', folder: 'math', icon: '\uD83E\uDDEE', suf: '-calculator' }, stat: { label: 'Statistics', cslug: 'statistics', folder: 'math', icon: '\uD83D\uDCCA', suf: '-calculator' }, geo: { label: 'Geometry', cslug: 'geometry', folder: 'math', icon: '\uD83D\uDCD0', suf: '-calculator' } };
  var defs = [];
  function T(id, name, cat, kw, blurb, def) { defs.push({ id: id, name: name, cat: cat, kw: kw, blurb: blurb, def: def }); }

  T('quadratic-equation', 'Quadratic Equation Calculator', 'math', 'quadratic equation calculator, quadratic formula', 'Solve ax\u00B2 + bx + c = 0 for real or complex roots.', { inputs: [{ k: 'a', label: 'a', v: 1, step: 'any' }, { k: 'b', label: 'b', v: -3, step: 'any' }, { k: 'c', label: 'c', v: 2, step: 'any' }], calc: function (v) { var d = v.b * v.b - 4 * v.a * v.c; if (d < 0) { var re = nf(-v.b / (2 * v.a), 3), im = nf(rt(-d) / (2 * v.a), 3); return [['Root 1', re + ' + ' + im + 'i'], ['Root 2', re + ' - ' + im + 'i'], ['Discriminant', nf(d, 3)]]; } return [['Root 1', nf((-v.b + rt(d)) / (2 * v.a), 4)], ['Root 2', nf((-v.b - rt(d)) / (2 * v.a), 4)], ['Discriminant', nf(d, 3)]]; } });
  T('factorial', 'Factorial Calculator', 'math', 'factorial calculator, n factorial', 'Calculate the factorial (n!) of a number.', { inputs: [{ k: 'n', label: 'n', v: 5, step: 1 }], calc: function (v) { return [['n!', nf(fact(v.n), 0)]]; } });
  T('permutation', 'Permutation Calculator', 'math', 'permutation calculator, nPr calculator', 'Calculate the number of permutations nPr.', { inputs: [{ k: 'n', label: 'n', v: 5, step: 1 }, { k: 'r', label: 'r', v: 2, step: 1 }], calc: function (v) { return [['nPr', nf(fact(v.n) / fact(v.n - v.r), 0)]]; } });
  T('combination', 'Combination Calculator', 'math', 'combination calculator, nCr calculator', 'Calculate the number of combinations nCr.', { inputs: [{ k: 'n', label: 'n', v: 5, step: 1 }, { k: 'r', label: 'r', v: 2, step: 1 }], calc: function (v) { return [['nCr', nf(fact(v.n) / (fact(v.r) * fact(v.n - v.r)), 0)]]; } });
  T('prime-number', 'Prime Number Checker', 'math', 'prime number checker, is it prime', 'Check whether a number is prime and find a factor.', { inputs: [{ k: 'n', label: 'Number', v: 17, step: 1 }], calc: function (v) { var n = fl(v.n); if (n < 2) return [['Prime?', 'No'], ['Reason', 'Less than 2']]; var f = 0; for (var i = 2; i <= rt(n); i++) { if (n % i === 0) { f = i; break; } } return [['Prime?', f ? 'No' : 'Yes'], ['Smallest factor', f ? f : n]]; } });
  T('fraction-simplify', 'Fraction Simplifier', 'math', 'fraction simplifier, simplify fraction', 'Reduce a fraction to its lowest terms.', { inputs: [{ k: 'n', label: 'Numerator', v: 8, step: 1 }, { k: 'd', label: 'Denominator', v: 12, step: 1 }], calc: function (v) { var g = gcd(v.n, v.d); return [['Simplified', (v.n / g) + '/' + (v.d / g)], ['Decimal', nf(v.n / v.d, 4)]]; } });
  T('decimal-to-fraction', 'Decimal to Fraction Calculator', 'math', 'decimal to fraction calculator', 'Convert a decimal number into a fraction.', { inputs: [{ k: 'x', label: 'Decimal', v: 0.75, step: 'any' }], calc: function (v) { var den = 1000000, num = rnd(v.x * den), g = gcd(num, den); return [['Fraction', (num / g) + '/' + (den / g)]]; } });
  T('scientific-notation', 'Scientific Notation Calculator', 'math', 'scientific notation calculator, standard form', 'Convert a number to scientific (standard) notation.', { inputs: [{ k: 'x', label: 'Number', v: 12345, step: 'any' }], calc: function (v) { if (v.x === 0) return [['Notation', '0']]; var e = fl(lg(ab(v.x)) / lg(10)); return [['Notation', nf(v.x / pw(10, e), 4) + ' \u00D7 10^' + e]]; } });
  T('log', 'Logarithm Calculator', 'math', 'logarithm calculator, log base calculator', 'Calculate the logarithm of a number to any base.', { inputs: [{ k: 'x', label: 'Number', v: 100, step: 'any' }, { k: 'b', label: 'Base', v: 10, step: 'any' }], calc: function (v) { return [['log', nf(lg(v.x) / lg(v.b), 5)], ['Natural log (ln)', nf(lg(v.x), 5)]]; } });
  T('antilog', 'Antilog Calculator', 'math', 'antilog calculator, inverse logarithm', 'Calculate the antilogarithm (inverse log) of a value.', { inputs: [{ k: 'x', label: 'Value', v: 2, step: 'any' }, { k: 'b', label: 'Base', v: 10, step: 'any' }], calc: function (v) { return [['Antilog', nf(pw(v.b, v.x), 4)]]; } });
  T('standard-deviation', 'Standard Deviation Calculator', 'stat', 'standard deviation calculator, sd calculator', 'Find mean, variance and standard deviation of a data set.', { inputs: [{ k: 'list', label: 'Numbers (comma separated)', t: 'text', v: '2, 4, 4, 4, 5, 5, 7, 9' }], calc: function (v) { var a = LIST(v.list), n = a.length; if (!n) return [['SD', 'Enter numbers']]; var mean = a.reduce(function (s, x) { return s + x; }, 0) / n; var vr = a.reduce(function (s, x) { return s + (x - mean) * (x - mean); }, 0) / n; return [['Mean', nf(mean, 3)], ['Variance', nf(vr, 3)], ['Std deviation', nf(rt(vr), 3)]]; } });
  T('variance', 'Variance Calculator', 'stat', 'variance calculator, population variance', 'Calculate the variance and mean of a data set.', { inputs: [{ k: 'list', label: 'Numbers (comma separated)', t: 'text', v: '10, 12, 23, 23, 16, 23, 21, 16' }], calc: function (v) { var a = LIST(v.list), n = a.length; if (!n) return [['Variance', 'Enter numbers']]; var mean = a.reduce(function (s, x) { return s + x; }, 0) / n; var vr = a.reduce(function (s, x) { return s + (x - mean) * (x - mean); }, 0) / n; return [['Variance', nf(vr, 3)], ['Mean', nf(mean, 3)]]; } });
  T('median-mode', 'Mean Median Mode Calculator', 'stat', 'mean median mode calculator', 'Find the mean, median and mode of numbers.', { inputs: [{ k: 'list', label: 'Numbers (comma separated)', t: 'text', v: '3, 5, 5, 6, 8, 9' }], calc: function (v) { var a = LIST(v.list).sort(function (x, y) { return x - y; }), n = a.length; if (!n) return [['Median', 'Enter numbers']]; var mean = a.reduce(function (s, x) { return s + x; }, 0) / n; var med = n % 2 ? a[(n - 1) / 2] : (a[n / 2 - 1] + a[n / 2]) / 2; var cnt = {}, best = a[0], bc = 0; a.forEach(function (x) { cnt[x] = (cnt[x] || 0) + 1; if (cnt[x] > bc) { bc = cnt[x]; best = x; } }); return [['Mean', nf(mean, 3)], ['Median', nf(med, 3)], ['Mode', bc > 1 ? best : 'None']]; } });
  T('z-score', 'Z-Score Calculator', 'stat', 'z score calculator, standard score', 'Calculate the z-score of a value.', { inputs: [{ k: 'x', label: 'Value', v: 80, step: 'any' }, { k: 'm', label: 'Mean', v: 70, step: 'any' }, { k: 'sd', label: 'Standard deviation', v: 10, step: 'any' }], calc: function (v) { return [['Z-score', nf((v.x - v.m) / v.sd, 3)]]; } });
  T('probability', 'Probability Calculator', 'stat', 'probability calculator, simple probability', 'Calculate the probability of an event.', { inputs: [{ k: 'f', label: 'Favourable outcomes', v: 1, step: 1 }, { k: 't', label: 'Total outcomes', v: 6, step: 1 }], calc: function (v) { return [['Probability', nf(v.f / v.t, 4)], ['Percentage', pct(v.f / v.t * 100)], ['Odds', v.f + ':' + (v.t - v.f)]]; } });
  T('circle-area', 'Circle Area Calculator', 'geo', 'circle area calculator, area of circle', 'Find the area and circumference of a circle.', { inputs: [{ k: 'r', label: 'Radius', v: 5, step: 'any' }], calc: function (v) { return [['Area', nf(PI * v.r * v.r, 3)], ['Circumference', nf(2 * PI * v.r, 3)], ['Diameter', nf(2 * v.r, 3)]]; } });
  T('triangle-area', 'Triangle Area Calculator', 'geo', 'triangle area calculator, area of triangle', 'Find the area of a triangle from base and height.', { inputs: [{ k: 'b', label: 'Base', v: 10, step: 'any' }, { k: 'h', label: 'Height', v: 5, step: 'any' }], calc: function (v) { return [['Area', nf(0.5 * v.b * v.h, 3)]]; } });
  T('trapezoid-area', 'Trapezoid Area Calculator', 'geo', 'trapezoid area calculator', 'Find the area of a trapezoid.', { inputs: [{ k: 'a', label: 'Side a', v: 6, step: 'any' }, { k: 'b', label: 'Side b', v: 10, step: 'any' }, { k: 'h', label: 'Height', v: 4, step: 'any' }], calc: function (v) { return [['Area', nf((v.a + v.b) / 2 * v.h, 3)]]; } });
  T('rectangle-area', 'Rectangle Area & Perimeter Calculator', 'geo', 'rectangle area perimeter calculator', 'Find the area and perimeter of a rectangle.', { inputs: [{ k: 'l', label: 'Length', v: 10, step: 'any' }, { k: 'w', label: 'Width', v: 5, step: 'any' }], calc: function (v) { return [['Area', nf(v.l * v.w, 3)], ['Perimeter', nf(2 * (v.l + v.w), 3)], ['Diagonal', nf(rt(v.l * v.l + v.w * v.w), 3)]]; } });
  T('cylinder-volume', 'Cylinder Volume Calculator', 'geo', 'cylinder volume calculator, volume of cylinder', 'Find the volume and surface area of a cylinder.', { inputs: [{ k: 'r', label: 'Radius', v: 3, step: 'any' }, { k: 'h', label: 'Height', v: 10, step: 'any' }], calc: function (v) { return [['Volume', nf(PI * v.r * v.r * v.h, 3)], ['Surface area', nf(2 * PI * v.r * (v.r + v.h), 3)]]; } });
  T('cone-volume', 'Cone Volume Calculator', 'geo', 'cone volume calculator, volume of cone', 'Find the volume of a cone.', { inputs: [{ k: 'r', label: 'Radius', v: 3, step: 'any' }, { k: 'h', label: 'Height', v: 9, step: 'any' }], calc: function (v) { return [['Volume', nf(PI * v.r * v.r * v.h / 3, 3)], ['Slant height', nf(rt(v.r * v.r + v.h * v.h), 3)]]; } });
  T('sphere-volume', 'Sphere Volume Calculator', 'geo', 'sphere volume calculator, volume of sphere', 'Find the volume and surface area of a sphere.', { inputs: [{ k: 'r', label: 'Radius', v: 5, step: 'any' }], calc: function (v) { return [['Volume', nf(4 / 3 * PI * pw(v.r, 3), 3)], ['Surface area', nf(4 * PI * v.r * v.r, 3)]]; } });
  T('pythagorean', 'Pythagorean Theorem Calculator', 'geo', 'pythagorean theorem calculator, hypotenuse', 'Find the hypotenuse from two right-triangle sides.', { inputs: [{ k: 'a', label: 'Side a', v: 3, step: 'any' }, { k: 'b', label: 'Side b', v: 4, step: 'any' }], calc: function (v) { return [['Hypotenuse', nf(rt(v.a * v.a + v.b * v.b), 4)]]; } });
  T('slope', 'Slope Calculator', 'geo', 'slope calculator, slope of a line', 'Find the slope and angle of a line between two points.', { inputs: [{ k: 'x1', label: 'x1', v: 1, step: 'any' }, { k: 'y1', label: 'y1', v: 2, step: 'any' }, { k: 'x2', label: 'x2', v: 4, step: 'any' }, { k: 'y2', label: 'y2', v: 8, step: 'any' }], calc: function (v) { if (v.x2 === v.x1) return [['Slope', 'Undefined (vertical)']]; var m = (v.y2 - v.y1) / (v.x2 - v.x1); return [['Slope', nf(m, 4)], ['Angle', nf(atan2(v.y2 - v.y1, v.x2 - v.x1) * 180 / PI, 2) + '\u00B0']]; } });
  T('distance-two-points', 'Distance Between Two Points Calculator', 'geo', 'distance between two points calculator', 'Find the distance between two coordinates.', { inputs: [{ k: 'x1', label: 'x1', v: 0, step: 'any' }, { k: 'y1', label: 'y1', v: 0, step: 'any' }, { k: 'x2', label: 'x2', v: 3, step: 'any' }, { k: 'y2', label: 'y2', v: 4, step: 'any' }], calc: function (v) { return [['Distance', nf(rt(pw(v.x2 - v.x1, 2) + pw(v.y2 - v.y1, 2)), 4)]]; } });
  T('midpoint', 'Midpoint Calculator', 'geo', 'midpoint calculator, midpoint of line', 'Find the midpoint between two coordinates.', { inputs: [{ k: 'x1', label: 'x1', v: 0, step: 'any' }, { k: 'y1', label: 'y1', v: 0, step: 'any' }, { k: 'x2', label: 'x2', v: 4, step: 'any' }, { k: 'y2', label: 'y2', v: 6, step: 'any' }], calc: function (v) { return [['Midpoint', '(' + nf((v.x1 + v.x2) / 2, 2) + ', ' + nf((v.y1 + v.y2) / 2, 2) + ')']]; } });
  T('arithmetic-progression', 'Arithmetic Progression Calculator', 'math', 'arithmetic progression calculator, ap sum', 'Find the nth term and sum of an arithmetic progression.', { inputs: [{ k: 'a', label: 'First term (a)', v: 2, step: 'any' }, { k: 'd', label: 'Common difference (d)', v: 3, step: 'any' }, { k: 'n', label: 'n', v: 10, step: 1 }], calc: function (v) { return [['nth term', nf(v.a + (v.n - 1) * v.d, 3)], ['Sum of n terms', nf(v.n / 2 * (2 * v.a + (v.n - 1) * v.d), 3)]]; } });
  T('geometric-progression', 'Geometric Progression Calculator', 'math', 'geometric progression calculator, gp sum', 'Find the nth term and sum of a geometric progression.', { inputs: [{ k: 'a', label: 'First term (a)', v: 2, step: 'any' }, { k: 'r', label: 'Common ratio (r)', v: 2, step: 'any' }, { k: 'n', label: 'n', v: 10, step: 1 }], calc: function (v) { var sum = v.r === 1 ? v.a * v.n : v.a * (pw(v.r, v.n) - 1) / (v.r - 1); return [['nth term', nf(v.a * pw(v.r, v.n - 1), 3)], ['Sum of n terms', nf(sum, 3)]]; } });
  T('modulo', 'Modulo Calculator', 'math', 'modulo calculator, remainder calculator', 'Find the remainder and quotient of a division.', { inputs: [{ k: 'a', label: 'Dividend (a)', v: 17, step: 'any' }, { k: 'b', label: 'Divisor (b)', v: 5, step: 'any' }], calc: function (v) { return [['a mod b', nf(v.a % v.b, 4)], ['Quotient', nf(fl(v.a / v.b), 0)]]; } });
  T('roman-numeral', 'Roman Numeral Converter', 'math', 'roman numeral converter, number to roman', 'Convert a number (1-3999) to Roman numerals.', { inputs: [{ k: 'n', label: 'Number (1-3999)', v: 2024, step: 1 }], calc: function (v) { return [['Roman numeral', roman(v.n)]]; } });

  var metaArr = defs.map(function (d) { var c = CMAP[d.cat]; return { id: d.id, name: d.name, cat: d.cat, label: c.label, kw: d.kw, blurb: d.blurb, slug: d.id + c.suf, folder: c.folder, cslug: c.cslug, icon: c.icon }; });
  if (isNode) { module.exports = { meta: metaArr, defs: defs, CMAP: CMAP }; return; }
  var CS = root.CS, SEO = root.SEO;
  if (!CS || !CS.Calc) return;
  defs.forEach(function (d) { var c = CMAP[d.cat]; if (CS.Calc.get && CS.Calc.get(d.id)) return; CS.Calc.register({ id: d.id, name: d.name, category: c.label, icon: c.icon, description: d.blurb, render: simple(d.def) }); });
  if (SEO && SEO.TOOLS) { defs.forEach(function (d) { var c = CMAP[d.cat]; if (!SEO.TOOLS[d.id]) { SEO.TOOLS[d.id] = { slug: d.id + c.suf, cat: c.cslug, icon: c.icon, name: d.name, title: d.name + ' | allfreecalculators.in', desc: d.blurb, keywords: d.kw, intro: d.blurb, options: [], faqs: [{ q: 'Is the ' + d.name + ' free?', a: 'Yes, it is 100% free with no sign-up.' }, { q: 'Does it work on mobile?', a: 'Yes, on any device in your browser.' }], related: [] }; if (SEO.ORDER && SEO.ORDER.indexOf(d.id) < 0) SEO.ORDER.push(d.id); } }); }
})(typeof self !== 'undefined' ? self : this);
