/* tools-web.js \u2013 Web & Developer tool family + SEO tool family (calc-engine based). */
(function (root) {
  'use strict';
  var isNode = (typeof module !== 'undefined' && module.exports);
  if (isNode) require('./tools-families.js');
  var SEO = isNode ? require('./seo-data.js') : root.SEO;
  var H = root.__megaHelpers; var mk = H.mk, push = H.push, num = H.num;
  function T(id, name, cat, icon, kw, blurb, def, faqs) { push({ id: id, slug: id, cat: cat, icon: icon, name: name, kw: kw, blurb: blurb, def: def, faqs: faqs }); }
  function b64enc(s) { try { return (typeof btoa !== 'undefined' ? btoa(unescape(encodeURIComponent(s))) : Buffer.from(s, 'utf8').toString('base64')); } catch (e) { return '(error)'; } }
  function b64dec(s) { try { return (typeof atob !== 'undefined' ? decodeURIComponent(escape(atob(s))) : Buffer.from(s, 'base64').toString('utf8')); } catch (e) { return '(invalid base64)'; } }

  var WD = 'Web & Developer Tools', wdi = '\uD83D\uDCBB';
  T('base64-encode', 'Base64 Encode', WD, wdi, 'base64 encode', 'Encode text to Base64.', mk({ inputs: [{ k: 't', label: 'Text', t: 'area', v: 'Hello World' }], calc: function (v) { return [['Base64', b64enc(String(v.t || ''))]]; } }));
  T('base64-decode', 'Base64 Decode', WD, wdi, 'base64 decode', 'Decode Base64 back to text.', mk({ inputs: [{ k: 't', label: 'Base64', t: 'area', v: 'SGVsbG8gV29ybGQ=' }], calc: function (v) { return [['Text', b64dec(String(v.t || '').trim())]]; } }));
  T('url-encode', 'URL Encode', WD, wdi, 'url encode, percent encode', 'Percent-encode text for safe use in URLs.', mk({ inputs: [{ k: 't', label: 'Text', t: 'area', v: 'hello world & more=1' }], calc: function (v) { return [['Encoded', encodeURIComponent(String(v.t || ''))]]; } }));
  T('url-decode', 'URL Decode', WD, wdi, 'url decode', 'Decode percent-encoded URL text.', mk({ inputs: [{ k: 't', label: 'Encoded', t: 'area', v: 'hello%20world%20%26%20more%3D1' }], calc: function (v) { try { return [['Decoded', decodeURIComponent(String(v.t || ''))]]; } catch (e) { return [['Decoded', '(invalid)']]; } } }));
  T('html-encode', 'HTML Encode', WD, wdi, 'html encode, escape html', 'Escape HTML special characters.', mk({ inputs: [{ k: 't', label: 'Text/HTML', t: 'area', v: '<a href="x">Tom & Jerry</a>' }], calc: function (v) { return [['Encoded', String(v.t || '').replace(/[&<>"\']/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]; })]]; } }));
  T('html-decode', 'HTML Decode', WD, wdi, 'html decode, unescape html', 'Decode HTML entities back to characters.', mk({ inputs: [{ k: 't', label: 'Encoded HTML', t: 'area', v: '&lt;b&gt;Tom &amp; Jerry&lt;/b&gt;' }], calc: function (v) { return [['Decoded', String(v.t || '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'")]]; } }));
  T('json-validator', 'JSON Validator', WD, wdi, 'json validator, validate json', 'Check whether text is valid JSON.', mk({ inputs: [{ k: 't', label: 'JSON', t: 'area', v: '{"name":"CalcSuite","tools":2500}' }], calc: function (v) { try { JSON.parse(v.t || ''); return [['Valid?', 'Yes \u2705']]; } catch (e) { return [['Valid?', 'No \u274C'], ['Error', e.message]]; } } }));
  T('json-minifier', 'JSON Minifier', WD, wdi, 'minify json', 'Compress JSON by removing whitespace.', mk({ inputs: [{ k: 't', label: 'JSON', t: 'area', v: '{\n  "a": 1,\n  "b": [1, 2, 3]\n}' }], calc: function (v) { try { return [['Minified', JSON.stringify(JSON.parse(v.t || ''))]]; } catch (e) { return [['Error', e.message]]; } } }));
  T('json-beautifier', 'JSON Beautifier', WD, wdi, 'format json, pretty print json', 'Pretty-print JSON with indentation.', mk({ inputs: [{ k: 't', label: 'JSON', t: 'area', v: '{"a":1,"b":[1,2,3]}' }], calc: function (v) { try { return [['Formatted', JSON.stringify(JSON.parse(v.t || ''), null, 2)]]; } catch (e) { return [['Error', e.message]]; } } }));
  T('csv-to-json', 'CSV to JSON', WD, wdi, 'csv to json', 'Convert CSV (with header row) to JSON.', mk({ inputs: [{ k: 't', label: 'CSV', t: 'area', v: 'name,age\nAlice,30\nBob,25' }], calc: function (v) { var lines = String(v.t || '').trim().split(/\n/); if (lines.length < 2) return [['JSON', '[]']]; var hdr = lines[0].split(','); var rows = lines.slice(1).map(function (l) { var c = l.split(','), o = {}; hdr.forEach(function (h, i) { o[h.trim()] = (c[i] || '').trim(); }); return o; }); return [['JSON', JSON.stringify(rows, null, 2)]]; } }));
  T('json-to-csv', 'JSON to CSV', WD, wdi, 'json to csv', 'Convert an array of JSON objects to CSV.', mk({ inputs: [{ k: 't', label: 'JSON array', t: 'area', v: '[{"name":"Alice","age":30},{"name":"Bob","age":25}]' }], calc: function (v) { try { var arr = JSON.parse(v.t || '[]'); if (!arr.length) return [['CSV', '']]; var hdr = Object.keys(arr[0]); var out = [hdr.join(',')]; arr.forEach(function (o) { out.push(hdr.map(function (h) { return o[h]; }).join(',')); }); return [['CSV', out.join('\n')]]; } catch (e) { return [['Error', e.message]]; } } }));
  T('jwt-decoder', 'JWT Decoder', WD, wdi, 'jwt decode', 'Decode the header and payload of a JWT (no verification).', mk({ inputs: [{ k: 't', label: 'JWT', t: 'area', v: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMiLCJuYW1lIjoiQWxpY2UifQ.abc' }], calc: function (v) { var p = String(v.t || '').split('.'); if (p.length < 2) return [['Error', 'Not a valid JWT']]; function d(x) { try { return b64dec(x.replace(/-/g, '+').replace(/_/g, '/')); } catch (e) { return '(error)'; } } return [['Header', d(p[0])], ['Payload', d(p[1])]]; } }));
  T('unix-to-date', 'Unix Timestamp to Date', WD, wdi, 'unix timestamp, epoch to date', 'Convert a Unix timestamp to a human date.', mk({ inputs: [{ k: 't', label: 'Unix timestamp (seconds)', v: 1700000000 }], calc: function (v) { var d = new Date(num(v.t) * 1000); return [['UTC', d.toUTCString()], ['ISO', d.toISOString()], ['Local', d.toString()]]; } }));
  T('date-to-unix', 'Date to Unix Timestamp', WD, wdi, 'date to epoch, timestamp', 'Convert a date to a Unix timestamp.', mk({ inputs: [{ k: 't', label: 'Date', t: 'date', v: '2026-01-01' }], calc: function (v) { var d = new Date(v.t || Date.now()); if (isNaN(d)) return [['Error', 'Invalid date']]; return [['Seconds', Math.floor(d.getTime() / 1000)], ['Milliseconds', d.getTime()]]; } }));
  T('regex-tester', 'Regex Tester', WD, wdi, 'regex tester, regular expression', 'Test a regular expression against sample text.', mk({ inputs: [{ k: 'p', label: 'Pattern', t: 'text', v: '\\d+' }, { k: 'f', label: 'Flags', t: 'text', v: 'g' }, { k: 't', label: 'Test text', t: 'area', v: 'There are 12 cats and 30 dogs.' }], calc: function (v) { try { var re = new RegExp(v.p || '', v.f || ''); var m = String(v.t || '').match(re); return [['Matches', m ? m.join(', ') : 'none'], ['Count', m ? m.length : 0]]; } catch (e) { return [['Error', e.message]]; } } }));
  T('css-minifier', 'CSS Minifier', WD, wdi, 'minify css', 'Minify CSS by removing comments and whitespace.', mk({ inputs: [{ k: 't', label: 'CSS', t: 'area', v: '.box {\n  color: red;\n  /* note */\n  margin: 0;\n}' }], calc: function (v) { return [['Minified', String(v.t || '').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s*([{}:;,])\s*/g, '$1').replace(/\s+/g, ' ').trim()]]; } }));
  T('number-to-words', 'Number to Words', WD, wdi, 'number to words, spell number', 'Convert a number into English words.', mk({ inputs: [{ k: 'n', label: 'Number', v: 12345 }], calc: function (v) { var n = Math.floor(num(v.n)); return [['In words', n2w(n)]]; } }));
  T('binary-to-decimal', 'Binary to Decimal', WD, wdi, 'binary to decimal', 'Convert a binary number to decimal.', mk({ inputs: [{ k: 't', label: 'Binary', t: 'text', v: '101010' }], calc: function (v) { var n = parseInt(String(v.t || '').trim(), 2); return [['Decimal', isNaN(n) ? '(invalid)' : n]]; } }));
  T('decimal-to-binary', 'Decimal to Binary', WD, wdi, 'decimal to binary', 'Convert a decimal number to binary.', mk({ inputs: [{ k: 'n', label: 'Decimal', v: 42 }], calc: function (v) { return [['Binary', (Math.floor(num(v.n)) >>> 0).toString(2)]]; } }));
  T('decimal-to-hex', 'Decimal to Hex', WD, wdi, 'decimal to hex', 'Convert a decimal number to hexadecimal.', mk({ inputs: [{ k: 'n', label: 'Decimal', v: 255 }], calc: function (v) { return [['Hex', Math.floor(num(v.n)).toString(16).toUpperCase()]]; } }));
  T('hex-to-decimal-num', 'Hex to Decimal', WD, wdi, 'hex to decimal', 'Convert a hexadecimal number to decimal.', mk({ inputs: [{ k: 't', label: 'Hex', t: 'text', v: 'FF' }], calc: function (v) { var n = parseInt(String(v.t || '').replace(/^0x/i, ''), 16); return [['Decimal', isNaN(n) ? '(invalid)' : n]]; } }));
  T('decimal-to-octal', 'Decimal to Octal', WD, wdi, 'decimal to octal', 'Convert a decimal number to octal.', mk({ inputs: [{ k: 'n', label: 'Decimal', v: 64 }], calc: function (v) { return [['Octal', Math.floor(num(v.n)).toString(8)]]; } }));
  T('octal-to-decimal', 'Octal to Decimal', WD, wdi, 'octal to decimal', 'Convert an octal number to decimal.', mk({ inputs: [{ k: 't', label: 'Octal', t: 'text', v: '100' }], calc: function (v) { var n = parseInt(String(v.t || '').trim(), 8); return [['Decimal', isNaN(n) ? '(invalid)' : n]]; } }));
  T('binary-to-hex', 'Binary to Hex', WD, wdi, 'binary to hex', 'Convert a binary number to hexadecimal.', mk({ inputs: [{ k: 't', label: 'Binary', t: 'text', v: '11111111' }], calc: function (v) { var n = parseInt(String(v.t || '').trim(), 2); return [['Hex', isNaN(n) ? '(invalid)' : n.toString(16).toUpperCase()]]; } }));
  T('hex-to-binary', 'Hex to Binary', WD, wdi, 'hex to binary', 'Convert a hexadecimal number to binary.', mk({ inputs: [{ k: 't', label: 'Hex', t: 'text', v: 'A5' }], calc: function (v) { var n = parseInt(String(v.t || '').replace(/^0x/i, ''), 16); return [['Binary', isNaN(n) ? '(invalid)' : n.toString(2)]]; } }));
  T('query-string-parser', 'Query String Parser', WD, wdi, 'parse query string, url params', 'Parse a URL query string into key/value pairs.', mk({ inputs: [{ k: 't', label: 'URL or query string', t: 'text', v: 'https://x.com?a=1&b=hello&c=true' }], calc: function (v) { var q = String(v.t || ''); var i = q.indexOf('?'); if (i >= 0) q = q.slice(i + 1); if (!q) return [['Params', 'none']]; return q.split('&').map(function (p) { var kv = p.split('='); return [decodeURIComponent(kv[0] || ''), decodeURIComponent(kv[1] || '')]; }); } }));
  T('utm-builder', 'UTM Campaign URL Builder', WD, wdi, 'utm builder, campaign url', 'Build a tracking URL with UTM parameters.', mk({ inputs: [{ k: 'u', label: 'Base URL', t: 'text', v: 'https://example.com' }, { k: 's', label: 'Source', t: 'text', v: 'newsletter' }, { k: 'm', label: 'Medium', t: 'text', v: 'email' }, { k: 'c', label: 'Campaign', t: 'text', v: 'launch' }], calc: function (v) { var p = []; if (v.s) p.push('utm_source=' + encodeURIComponent(v.s)); if (v.m) p.push('utm_medium=' + encodeURIComponent(v.m)); if (v.c) p.push('utm_campaign=' + encodeURIComponent(v.c)); return [['Tracking URL', (v.u || '') + (p.length ? (String(v.u).indexOf('?') >= 0 ? '&' : '?') + p.join('&') : '')]]; } }));
  T('http-status-lookup', 'HTTP Status Code Lookup', WD, wdi, 'http status code', 'Look up the meaning of an HTTP status code.', mk({ inputs: [{ k: 'c', label: 'Status code', v: 404 }], calc: function (v) { var M = { 200: 'OK', 201: 'Created', 204: 'No Content', 301: 'Moved Permanently', 302: 'Found', 304: 'Not Modified', 400: 'Bad Request', 401: 'Unauthorized', 403: 'Forbidden', 404: 'Not Found', 405: 'Method Not Allowed', 408: 'Request Timeout', 409: 'Conflict', 418: "I'm a teapot", 429: 'Too Many Requests', 500: 'Internal Server Error', 502: 'Bad Gateway', 503: 'Service Unavailable', 504: 'Gateway Timeout' }; var c = Math.floor(num(v.c)); return [['Code', c], ['Meaning', M[c] || 'Unknown / non-standard']]; } }));
  T('mime-type-lookup', 'MIME Type Lookup', WD, wdi, 'mime type', 'Find the MIME type for a file extension.', mk({ inputs: [{ k: 'e', label: 'Extension', t: 'text', v: 'png' }], calc: function (v) { var M = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp', svg: 'image/svg+xml', pdf: 'application/pdf', json: 'application/json', html: 'text/html', css: 'text/css', js: 'text/javascript', txt: 'text/plain', csv: 'text/csv', mp4: 'video/mp4', mp3: 'audio/mpeg', zip: 'application/zip', doc: 'application/msword', xls: 'application/vnd.ms-excel' }; var e = String(v.e || '').replace(/^\./, '').toLowerCase(); return [['MIME type', M[e] || 'application/octet-stream']]; } }));
  T('password-entropy', 'Password Entropy Calculator', WD, wdi, 'password entropy, password strength', 'Estimate the entropy and strength of a password.', mk({ inputs: [{ k: 't', label: 'Password', t: 'text', v: 'P@ssw0rd123' }], calc: function (v) { var p = String(v.t || ''); var pool = 0; if (/[a-z]/.test(p)) pool += 26; if (/[A-Z]/.test(p)) pool += 26; if (/[0-9]/.test(p)) pool += 10; if (/[^A-Za-z0-9]/.test(p)) pool += 32; var bits = p.length * (pool ? Math.log2(pool) : 0); var lab = bits < 40 ? 'Weak' : bits < 60 ? 'Reasonable' : bits < 80 ? 'Strong' : 'Very strong'; return [['Entropy', bits.toFixed(1) + ' bits'], ['Strength', lab], ['Character pool', pool]]; } }));
  T('text-diff-checker', 'Text Diff Checker', WD, wdi, 'text diff, compare text', 'Compare two texts line by line.', mk({ inputs: [{ k: 'a', label: 'Original', t: 'area', v: 'line one\nline two\nline three' }, { k: 'b', label: 'Changed', t: 'area', v: 'line one\nline 2\nline three' }], calc: function (v) { var A = String(v.a || '').split(/\n/), B = String(v.b || '').split(/\n/); var n = Math.max(A.length, B.length), diff = 0, out = []; for (var i = 0; i < n; i++) { if (A[i] !== B[i]) { diff++; out.push(['Line ' + (i + 1), '"' + (A[i] || '') + '" \u2192 "' + (B[i] || '') + '"']); } } return [['Changed lines', diff]].concat(out.slice(0, 20)); } }));
  T('snake-case-converter', 'snake_case Converter', WD, wdi, 'snake case', 'Convert text to snake_case.', mk({ inputs: [{ k: 't', label: 'Text', t: 'text', v: 'Hello World Example' }], calc: function (v) { return [['snake_case', String(v.t || '').trim().replace(/[^a-zA-Z0-9]+/g, '_').replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase().replace(/^_+|_+$/g, '')]]; } }));
  T('camel-case-converter', 'camelCase Converter', WD, wdi, 'camel case', 'Convert text to camelCase.', mk({ inputs: [{ k: 't', label: 'Text', t: 'text', v: 'hello world example' }], calc: function (v) { var w = String(v.t || '').split(/[^a-zA-Z0-9]+/).filter(Boolean); return [['camelCase', w.map(function (x, i) { x = x.toLowerCase(); return i ? x.charAt(0).toUpperCase() + x.slice(1) : x; }).join('')]]; } }));
  T('kebab-case-converter', 'kebab-case Converter', WD, wdi, 'kebab case', 'Convert text to kebab-case.', mk({ inputs: [{ k: 't', label: 'Text', t: 'text', v: 'Hello World Example' }], calc: function (v) { return [['kebab-case', String(v.t || '').trim().replace(/([a-z])([A-Z])/g, '$1-$2').replace(/[^a-zA-Z0-9]+/g, '-').toLowerCase().replace(/^-+|-+$/g, '')]]; } }));
  T('strip-html-tags', 'Strip HTML Tags', WD, wdi, 'remove html tags', 'Remove all HTML tags, leaving plain text.', mk({ inputs: [{ k: 't', label: 'HTML', t: 'area', v: '<p>Hello <b>world</b></p>' }], calc: function (v) { return [['Plain text', String(v.t || '').replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim()]]; } }));
  T('string-hash', 'String Hash (djb2)', WD, wdi, 'string hash, checksum', 'Compute a fast non-cryptographic djb2 hash of text.', mk({ inputs: [{ k: 't', label: 'Text', t: 'text', v: 'CalcSuite' }], calc: function (v) { var s = String(v.t || ''), h = 5381; for (var i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) >>> 0; return [['djb2 hash', h], ['Hex', h.toString(16)]]; } }), [{ q: 'Is this a secure hash?', a: 'No \u2013 djb2 is a fast non-cryptographic hash for checksums and lookups, not for passwords or security.' }]);

  /* ===== SEO Tools family ===== */
  var SO = 'SEO Tools', soi = '\uD83D\uDD0D';
  T('meta-title-length-checker', 'Meta Title Length Checker', SO, soi, 'meta title length, seo title', 'Check if your meta title fits within search-result limits.', mk({ inputs: [{ k: 't', label: 'Meta title', t: 'text', v: 'Free Online Calculator Suite \u2013 2500+ Tools' }], calc: function (v) { var l = String(v.t || '').length; return [['Characters', l], ['Status', l === 0 ? 'Empty' : l <= 60 ? 'Good \u2705' : 'Too long \u26A0\uFE0F (aim \u2264 60)'], ['Pixel estimate', Math.round(l * 9) + 'px']]; } }));
  T('meta-description-checker', 'Meta Description Checker', SO, soi, 'meta description length', 'Check if your meta description length is optimal.', mk({ inputs: [{ k: 't', label: 'Meta description', t: 'area', v: 'Use 2500+ free online calculators and converters.' }], calc: function (v) { var l = String(v.t || '').length; return [['Characters', l], ['Status', l === 0 ? 'Empty' : l < 120 ? 'A bit short' : l <= 160 ? 'Good \u2705' : 'Too long \u26A0\uFE0F (aim \u2264 160)']]; } }));
  T('keyword-density-checker', 'Keyword Density Checker', SO, soi, 'keyword density', 'Find the most frequent keywords and their density.', mk({ inputs: [{ k: 't', label: 'Content', t: 'area', v: 'SEO tools help SEO. Use these SEO tools for better SEO.' }], calc: function (v) { var w = String(v.t || '').toLowerCase().replace(/[^\w\s]/g, '').split(/\s+/).filter(Boolean); var c = {}; w.forEach(function (x) { c[x] = (c[x] || 0) + 1; }); var top = Object.keys(c).sort(function (a, b) { return c[b] - c[a]; }).slice(0, 8); return top.map(function (k) { return [k, c[k] + ' (' + (w.length ? (c[k] / w.length * 100).toFixed(1) : 0) + '%)']; }); } }));
  T('slug-seo-checker', 'SEO Slug Generator', SO, soi, 'seo slug, url optimizer', 'Generate a clean, SEO-friendly URL slug from a title.', mk({ inputs: [{ k: 't', label: 'Title', t: 'text', v: 'The Best SEO Tips for 2026!' }], calc: function (v) { return [['Slug', String(v.t || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')]]; } }));
  T('reading-time-estimator', 'Reading Time Estimator', SO, soi, 'reading time', 'Estimate how long content takes to read.', mk({ inputs: [{ k: 't', label: 'Content', t: 'area', v: 'Paste your article here to estimate reading time.' }, { k: 'wpm', label: 'Words per minute', v: 200 }], calc: function (v) { var w = (String(v.t || '').trim().match(/\S+/g) || []).length; var wpm = Math.max(50, num(v.wpm)); return [['Words', w], ['Reading time', Math.max(1, Math.ceil(w / wpm)) + ' min']]; } }));
  T('robots-txt-generator', 'Robots.txt Generator', SO, soi, 'robots txt generator', 'Generate a basic robots.txt file.', mk({ inputs: [{ k: 'a', label: 'Allow all crawlers?', t: 'sel', v: 'yes', opts: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No (block all)' }] }, { k: 's', label: 'Sitemap URL', t: 'text', v: 'https://example.com/sitemap.xml' }], calc: function (v) { var out = 'User-agent: *\n' + (v.a === 'no' ? 'Disallow: /' : 'Disallow:') + (v.s ? '\nSitemap: ' + v.s : ''); return [['robots.txt', out]]; } }));
  T('open-graph-generator', 'Open Graph Tag Generator', SO, soi, 'open graph, og tags', 'Generate Open Graph meta tags for social sharing.', mk({ inputs: [{ k: 't', label: 'Title', t: 'text', v: 'My Page' }, { k: 'd', label: 'Description', t: 'text', v: 'A great page' }, { k: 'u', label: 'URL', t: 'text', v: 'https://example.com' }], calc: function (v) { var o = '<meta property="og:title" content="' + (v.t || '') + '">\n<meta property="og:description" content="' + (v.d || '') + '">\n<meta property="og:url" content="' + (v.u || '') + '">\n<meta property="og:type" content="website">'; return [['OG tags', o]]; } }));

  function n2w(n) { if (n === 0) return 'zero'; if (n < 0) return 'negative ' + n2w(-n); var a = ['', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen']; var b = ['', '', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety']; function below1000(x) { var s = ''; if (x >= 100) { s += a[Math.floor(x / 100)] + ' hundred'; x %= 100; if (x) s += ' '; } if (x >= 20) { s += b[Math.floor(x / 10)]; if (x % 10) s += '-' + a[x % 10]; } else if (x > 0) s += a[x]; return s; } var sc = [['', 1], ['thousand', 1e3], ['million', 1e6], ['billion', 1e9], ['trillion', 1e12]]; var parts = []; for (var i = sc.length - 1; i >= 0; i--) { var unit = sc[i][1]; if (n >= unit) { var chunk = Math.floor(n / unit); n %= unit; parts.push(below1000(chunk) + (sc[i][0] ? ' ' + sc[i][0] : '')); } } return parts.join(' ').trim(); }

  if (isNode) module.exports = SEO;
})(typeof window !== 'undefined' ? window : globalThis);
