/* allfreecalculators.in - group D (Everyday, 25). Self-contained. */
(function (root) {
  'use strict';
  var isNode = (typeof module !== 'undefined' && module.exports);
  var pw = Math.pow, rt = Math.sqrt, ab = Math.abs, mx = Math.max, mn = Math.min, rnd = Math.round, fl = Math.floor, ce = Math.ceil, DAY = 86400000;
  function nf(n, d) { d = d == null ? 2 : d; return isFinite(n) ? Number(n).toLocaleString('en-IN', { maximumFractionDigits: d }) : '\u2014'; }
  function money(n) { return isFinite(n) ? '\u20B9' + Number(n).toLocaleString('en-IN', { maximumFractionDigits: 0 }) : '\u2014'; }
  function pct(n) { return isFinite(n) ? nf(n, 2) + '%' : '\u2014'; }
  function opt(v, l) { return { value: v, label: l }; }
  function pdate(s) { if (!s) return null; var d = new Date(s); return isNaN(d.getTime()) ? null : d; }
  function fmtD(d) { if (!d) return '\u2014'; return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }); }
  function hashN(s) { s = String(s || '').toLowerCase(); var h = 0; for (var i = 0; i < s.length; i++) { h = (h * 31 + s.charCodeAt(i)) % 100000; } return h; }
  function letterSum(s) { s = String(s || '').toUpperCase(); var t = 0; for (var i = 0; i < s.length; i++) { var c = s.charCodeAt(i); if (c >= 65 && c <= 90) t += ((c - 64 - 1) % 9) + 1; } return t; }
  function digitRoot(n) { n = ab(fl(n)); while (n > 9) { var s = 0; while (n) { s += n % 10; n = fl(n / 10); } n = s; } return n; }
  function simple(def) { return function () { var el = CS.el, wrap = el('div', { class: 'simplecalc' }); var grid = el('div', { class: 'cs-grid' }), inputs = {}; def.inputs.forEach(function (f) { var node; if (f.t === 'sel') node = CS.selectInput(f.opts, { value: f.v, onchange: run }); else if (f.t === 'ta') { node = el('textarea', { rows: f.rows || 5, style: 'width:100%;min-height:110px' }); node.value = f.v != null ? f.v : ''; node.addEventListener('input', run); } else if (f.t === 'date' || f.t === 'time' || f.t === 'text') { node = el('input', { type: f.t, value: f.v != null ? f.v : '' }); node.addEventListener('input', run); node.addEventListener('change', run); } else node = CS.numInput({ value: f.v, step: f.step, oninput: run }); inputs[f.k] = node; grid.appendChild(CS.field(f.label, node, f.hint)); }); var res = el('div', { class: 'result-area' }); wrap.appendChild(grid); wrap.appendChild(res); function readv() { var o = {}; def.inputs.forEach(function (f) { var n = inputs[f.k]; o[f.k] = (f.t === 'sel' || f.t === 'date' || f.t === 'time' || f.t === 'text' || f.t === 'ta') ? n.value : parseFloat(n.value); }); return o; } function run() { var out; try { out = def.calc(readv()); } catch (e) { out = [['Error', 'Check your inputs']]; } res.innerHTML = ''; if (!out || !out.length) return; var row = el('div', { class: 'kpi-row' }); out.forEach(function (p) { row.appendChild(CS.kpi(p[0], p[1], { class: p[2] || '' })); }); res.appendChild(row); } setTimeout(run, 0); return wrap; }; }
  var CMAP = { every: { label: 'Everyday', cslug: 'everyday', folder: 'everyday', icon: '\uD83C\uDFE0', suf: '-calculator' } };
  var defs = [];
  function T(id, name, kw, blurb, def) { defs.push({ id: id, name: name, cat: 'every', kw: kw, blurb: blurb, def: def }); }

  T('recipe-scaler', 'Recipe Scaler Calculator', 'recipe scaler calculator, scale recipe servings', 'Scale any recipe ingredient up or down by servings.', { inputs: [{ k: 'orig', label: 'Original servings', v: 4, step: 1 }, { k: 'want', label: 'Desired servings', v: 6, step: 1 }, { k: 'amt', label: 'Ingredient amount', v: 200, step: 'any' }], calc: function (v) { var f = v.want / v.orig; return [['Scaling factor', nf(f, 2) + '\u00D7'], ['Scaled amount', nf(v.amt * f, 2)]]; } });
  T('mobile-data-usage', 'Mobile Data Usage Calculator', 'mobile data usage calculator, monthly data', 'Estimate your monthly mobile data usage.', { inputs: [{ k: 'gb', label: 'Daily usage (GB)', v: 1.5, step: 'any' }], calc: function (v) { return [['Monthly usage', nf(v.gb * 30, 1) + ' GB'], ['Yearly usage', nf(v.gb * 365, 0) + ' GB']]; } });
  T('ac-tonnage', 'AC Tonnage Calculator', 'ac tonnage calculator, ac size for room', 'Find the right air-conditioner tonnage for your room.', { inputs: [{ k: 'area', label: 'Room area (sq ft)', v: 150, step: 'any' }], calc: function (v) { var ton = v.area / 130; return [['Recommended tonnage', nf(mx(0.8, ton), 1) + ' ton'], ['Cooling need', nf(v.area * 30, 0) + ' BTU']]; } });
  T('generator-size', 'Generator Size Calculator', 'generator size calculator, generator kva', 'Find the generator size (kVA) for your total load.', { inputs: [{ k: 'w', label: 'Total load (watts)', v: 3000, step: 'any' }, { k: 'pf', label: 'Power factor', v: 0.8, step: 'any' }], calc: function (v) { return [['Required kVA', nf(v.w / (v.pf * 1000), 2) + ' kVA'], ['With 20% margin', nf(v.w * 1.2 / (v.pf * 1000), 2) + ' kVA']]; } });
  T('solar-panel', 'Solar Panel Calculator', 'solar panel calculator, solar system size', 'Estimate the solar system size for your monthly usage.', { inputs: [{ k: 'units', label: 'Monthly units (kWh)', v: 300, step: 'any' }, { k: 'sun', label: 'Peak sun hours/day', v: 4.5, step: 'any' }], calc: function (v) { var kw = v.units / 30 / v.sun; return [['System size', nf(kw, 2) + ' kW'], ['Panels (400W)', ce(kw * 1000 / 400) + ' panels']]; } });
  T('lpg-cost', 'LPG Cost Calculator', 'lpg cost calculator, gas cylinder cost', 'Estimate your monthly and yearly LPG cost.', { inputs: [{ k: 'price', label: 'Cylinder price', v: 900, step: 'any' }, { k: 'peryear', label: 'Cylinders per year', v: 10, step: 1 }], calc: function (v) { return [['Yearly cost', money(v.price * v.peryear)], ['Monthly average', money(v.price * v.peryear / 12)]]; } });
  T('age-difference', 'Age Difference Calculator', 'age difference calculator, age gap', 'Find the age difference between two dates.', { inputs: [{ k: 'd1', label: 'First date', t: 'date', v: '1995-01-01' }, { k: 'd2', label: 'Second date', t: 'date', v: '2000-06-15' }], calc: function (v) { var a = pdate(v.d1), b = pdate(v.d2); if (!a || !b) return [['Difference', 'Enter both dates']]; var diff = ab(b - a); return [['Years', nf(diff / (365.25 * DAY), 1)], ['Days', nf(diff / DAY, 0)]]; } });
  T('love-percentage', 'Love Percentage Calculator', 'love percentage calculator, love flames', 'A fun compatibility score between two names.', { inputs: [{ k: 'a', label: 'Your name', t: 'text', v: 'Rahul' }, { k: 'b', label: 'Partner name', t: 'text', v: 'Priya' }], calc: function (v) { var s = hashN(v.a + v.b) + hashN(v.b + v.a); return [['Love score', (40 + s % 61) + '%']]; } });
  T('name-numerology', 'Name Numerology Calculator', 'name numerology calculator, numerology number', 'Find your numerology number from your name.', { inputs: [{ k: 'name', label: 'Full name', t: 'text', v: 'Rahul Sharma' }], calc: function (v) { var t = letterSum(v.name); return [['Total', t], ['Numerology number', digitRoot(t)]]; } });
  T('dice-roller', 'Dice Roller', 'dice roller, roll dice online', 'Roll one or more dice online.', { inputs: [{ k: 'sides', label: 'Sides per die', v: 6, step: 1 }, { k: 'count', label: 'Number of dice', v: 2, step: 1 }], calc: function (v) { var rolls = [], sum = 0; for (var i = 0; i < v.count; i++) { var r = 1 + fl(Math.random() * v.sides); rolls.push(r); sum += r; } return [['Rolls', rolls.join(', ')], ['Total', sum]]; } });
  T('random-number', 'Random Number Generator', 'random number generator, random number picker', 'Generate a random number in a range.', { inputs: [{ k: 'min', label: 'Minimum', v: 1, step: 1 }, { k: 'max', label: 'Maximum', v: 100, step: 1 }], calc: function (v) { return [['Random number', fl(v.min + Math.random() * (v.max - v.min + 1))]]; } });
  T('coin-flip', 'Coin Flip', 'coin flip, flip a coin online', 'Flip one or more coins online.', { inputs: [{ k: 'n', label: 'Number of flips', v: 1, step: 1 }], calc: function (v) { var h = 0; for (var i = 0; i < v.n; i++) if (Math.random() < 0.5) h++; return [['Heads', h], ['Tails', v.n - h]]; } });
  T('split-expense', 'Split Expense Calculator', 'split expense calculator, split bill', 'Split a bill equally between people.', { inputs: [{ k: 'total', label: 'Total amount', v: 2400, step: 'any' }, { k: 'people', label: 'Number of people', v: 4, step: 1 }, { k: 'tip', label: 'Tip (%)', v: 0, step: 'any' }], calc: function (v) { var t = v.total * (1 + v.tip / 100); return [['Total with tip', money(t)], ['Per person', money(t / v.people)]]; } });
  T('grocery-budget', 'Grocery Budget Calculator', 'grocery budget calculator, monthly grocery budget', 'Plan a monthly grocery budget from your income.', { inputs: [{ k: 'income', label: 'Monthly income', v: 50000, step: 'any' }, { k: 'pct', label: 'Grocery share (%)', v: 12, step: 'any' }], calc: function (v) { var b = v.income * v.pct / 100; return [['Monthly budget', money(b)], ['Weekly budget', money(b / 4.33)]]; } });
  T('salary-hike', 'Salary Hike Percentage Calculator', 'salary hike percentage calculator', 'Find the percentage hike between two salaries.', { inputs: [{ k: 'old', label: 'Old salary', v: 40000, step: 'any' }, { k: 'nw', label: 'New salary', v: 50000, step: 'any' }], calc: function (v) { return [['Hike', pct((v.nw - v.old) / v.old * 100)], ['Increase', money(v.nw - v.old)]]; } });
  T('salary-hike-amount', 'New Salary After Hike Calculator', 'new salary after hike calculator', 'Find your new salary after a percentage hike.', { inputs: [{ k: 'cur', label: 'Current salary', v: 40000, step: 'any' }, { k: 'hike', label: 'Hike (%)', v: 20, step: 'any' }], calc: function (v) { return [['New salary', money(v.cur * (1 + v.hike / 100))], ['Increase', money(v.cur * v.hike / 100)]]; } });
  T('notice-period', 'Notice Period End Date Calculator', 'notice period calculator, last working day', 'Find your last working day from a notice period.', { inputs: [{ k: 'start', label: 'Resignation date', t: 'date', v: '2026-01-01' }, { k: 'days', label: 'Notice period (days)', v: 60, step: 1 }], calc: function (v) { var d = pdate(v.start); if (!d) return [['Last day', 'Enter a date']]; return [['Last working day', fmtD(new Date(d.getTime() + v.days * DAY))]]; } });
  T('work-hours', 'Work Hours Calculator', 'work hours calculator, hours worked', 'Calculate hours worked between start and end time.', { inputs: [{ k: 'start', label: 'Start time', t: 'time', v: '09:00' }, { k: 'end', label: 'End time', t: 'time', v: '18:00' }, { k: 'brk', label: 'Break (minutes)', v: 60, step: 1 }], calc: function (v) { function m(t) { if (!t) return 0; var p = t.split(':'); return +p[0] * 60 + +p[1]; } var diff = m(v.end) - m(v.start); if (diff < 0) diff += 1440; diff -= v.brk; return [['Hours worked', nf(diff / 60, 2) + ' h'], ['Minutes', nf(diff, 0)]]; } });
  T('overtime-pay', 'Overtime Pay Calculator', 'overtime pay calculator, ot pay', 'Calculate overtime pay from hours and rate.', { inputs: [{ k: 'rate', label: 'Hourly rate', v: 200, step: 'any' }, { k: 'hrs', label: 'Overtime hours', v: 10, step: 'any' }, { k: 'mult', label: 'OT multiplier', v: 1.5, step: 'any' }], calc: function (v) { return [['Overtime pay', money(v.rate * v.hrs * v.mult)], ['Per OT hour', money(v.rate * v.mult)]]; } });
  T('electricity-cost', 'Electricity Cost Calculator', 'electricity cost calculator, appliance running cost', 'Estimate the running cost of an appliance.', { inputs: [{ k: 'w', label: 'Power (watts)', v: 1000, step: 'any' }, { k: 'hrs', label: 'Hours per day', v: 5, step: 'any' }, { k: 'rate', label: 'Rate per unit', v: 8, step: 'any' }], calc: function (v) { var daily = v.w / 1000 * v.hrs * v.rate; return [['Daily cost', money(daily)], ['Monthly cost', money(daily * 30)], ['Units/month', nf(v.w / 1000 * v.hrs * 30, 1)]]; } });
  T('water-tank', 'Water Tank Capacity Calculator', 'water tank capacity calculator, tank litres', 'Find the capacity of a water tank in litres.', { inputs: [{ k: 'l', label: 'Length (m)', v: 1, step: 'any' }, { k: 'w', label: 'Width (m)', v: 1, step: 'any' }, { k: 'h', label: 'Height (m)', v: 1, step: 'any' }], calc: function (v) { return [['Capacity', nf(v.l * v.w * v.h * 1000, 0) + ' litres'], ['Cubic metres', nf(v.l * v.w * v.h, 3)]]; } });
  T('room-area', 'Room Area Calculator', 'room area calculator, floor area', 'Find the floor area of a room.', { inputs: [{ k: 'l', label: 'Length (ft)', v: 12, step: 'any' }, { k: 'w', label: 'Width (ft)', v: 10, step: 'any' }], calc: function (v) { return [['Area', nf(v.l * v.w, 1) + ' sq ft'], ['In sq metres', nf(v.l * v.w * 0.092903, 2)]]; } });
  T('fuel-average', 'Fuel Average (Mileage) Calculator', 'fuel average calculator, mileage calculator', 'Calculate your vehicle mileage (km per litre).', { inputs: [{ k: 'd', label: 'Distance (km)', v: 400, step: 'any' }, { k: 'f', label: 'Fuel used (litres)', v: 25, step: 'any' }], calc: function (v) { return [['Mileage', nf(v.d / v.f, 2) + ' km/l'], ['Fuel per 100km', nf(v.f / v.d * 100, 2) + ' L']]; } });
  T('carpet-area', 'Carpet Area Calculator', 'carpet area calculator, builtup to carpet area', 'Convert built-up area to carpet area.', { inputs: [{ k: 'bu', label: 'Built-up area (sq ft)', v: 1000, step: 'any' }, { k: 'load', label: 'Loading (%)', v: 30, step: 'any' }], calc: function (v) { return [['Carpet area', nf(v.bu / (1 + v.load / 100), 1) + ' sq ft']]; } });
  T('discount', 'Discount Percentage Calculator', 'discount percentage calculator, discount calculator', 'Find the discount percentage and amount saved.', { inputs: [{ k: 'mrp', label: 'Original price', v: 2000, step: 'any' }, { k: 'price', label: 'Final price', v: 1500, step: 'any' }], calc: function (v) { return [['Discount', pct((v.mrp - v.price) / v.mrp * 100)], ['You save', money(v.mrp - v.price)]]; } });

  var metaArr = defs.map(function (d) { var c = CMAP[d.cat]; return { id: d.id, name: d.name, cat: d.cat, label: c.label, kw: d.kw, blurb: d.blurb, slug: d.id + c.suf, folder: c.folder, cslug: c.cslug, icon: c.icon }; });
  if (isNode) { module.exports = { meta: metaArr, defs: defs, CMAP: CMAP }; return; }
  var CS = root.CS, SEO = root.SEO;
  if (!CS || !CS.Calc) return;
  defs.forEach(function (d) { var c = CMAP[d.cat]; if (CS.Calc.get && CS.Calc.get(d.id)) return; CS.Calc.register({ id: d.id, name: d.name, category: c.label, icon: c.icon, description: d.blurb, render: simple(d.def) }); });
  if (SEO && SEO.TOOLS) { defs.forEach(function (d) { var c = CMAP[d.cat]; if (!SEO.TOOLS[d.id]) { SEO.TOOLS[d.id] = { slug: d.id + c.suf, cat: c.cslug, icon: c.icon, name: d.name, title: d.name + ' | allfreecalculators.in', desc: d.blurb, keywords: d.kw, intro: d.blurb, options: [], faqs: [{ q: 'Is the ' + d.name + ' free?', a: 'Yes, it is 100% free with no sign-up.' }, { q: 'Does it work on mobile?', a: 'Yes, on any device in your browser.' }], related: [] }; if (SEO.ORDER && SEO.ORDER.indexOf(d.id) < 0) SEO.ORDER.push(d.id); } }); }
})(typeof self !== 'undefined' ? self : this);
