/* allfreecalculators.in - group G (Text, 20) + group H (Converters, 20). Self-contained. */
(function (root) {
  'use strict';
  var isNode = (typeof module !== 'undefined' && module.exports);
  var fl = Math.floor, rnd = Math.round, mx = Math.max, mn = Math.min;
  function nf(n, d) { d = d == null ? 2 : d; return isFinite(n) ? Number(n).toLocaleString('en-IN', { maximumFractionDigits: d }) : '\u2014'; }
  function opt(v, l) { return { value: v, label: l }; }
  function words(s) { s = String(s || '').trim(); return s ? s.split(/\s+/) : []; }
  function sentences(s) { return String(s || '').split(/[.!?]+/).filter(function (x) { return x.trim(); }).length; }
  var MORSE = { a: '.-', b: '-...', c: '-.-.', d: '-..', e: '.', f: '..-.', g: '--.', h: '....', i: '..', j: '.---', k: '-.-', l: '.-..', m: '--', n: '-.', o: '---', p: '.--.', q: '--.-', r: '.-.', s: '...', t: '-', u: '..-', v: '...-', w: '.--', x: '-..-', y: '-.--', z: '--..', '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....', '6': '-....', '7': '--...', '8': '---..', '9': '----.' };
  var MORSE_R = {}; for (var mk in MORSE) { if (MORSE.hasOwnProperty(mk)) MORSE_R[MORSE[mk]] = mk; }
  function simple(def) { return function () { var el = CS.el, wrap = el('div', { class: 'simplecalc' }); var grid = el('div', { class: 'cs-grid' }), inputs = {}; def.inputs.forEach(function (f) { var node; if (f.t === 'sel') node = CS.selectInput(f.opts, { value: f.v, onchange: run }); else if (f.t === 'ta') { node = el('textarea', { rows: f.rows || 5, style: 'width:100%;min-height:110px' }); node.value = f.v != null ? f.v : ''; node.addEventListener('input', run); } else if (f.t === 'date' || f.t === 'time' || f.t === 'text') { node = el('input', { type: f.t, value: f.v != null ? f.v : '' }); node.addEventListener('input', run); node.addEventListener('change', run); } else node = CS.numInput({ value: f.v, step: f.step, oninput: run }); inputs[f.k] = node; grid.appendChild(CS.field(f.label, node, f.hint)); }); var res = el('div', { class: 'result-area' }); wrap.appendChild(grid); wrap.appendChild(res); function readv() { var o = {}; def.inputs.forEach(function (f) { var n = inputs[f.k]; o[f.k] = (f.t === 'sel' || f.t === 'date' || f.t === 'time' || f.t === 'text' || f.t === 'ta') ? n.value : parseFloat(n.value); }); return o; } function run() { var out; try { out = def.calc(readv()); } catch (e) { out = [['Error', 'Check your inputs']]; } res.innerHTML = ''; if (!out || !out.length) return; var row = el('div', { class: 'kpi-row' }); out.forEach(function (p) { row.appendChild(CS.kpi(p[0], p[1], { class: p[2] || '' })); }); res.appendChild(row); } setTimeout(run, 0); return wrap; }; }
  var CMAP = { text: { label: 'Text', cslug: 'text-tools', folder: 'text', icon: '\uD83D\uDCDD', suf: '-tool' }, conv: { label: 'Converters', cslug: 'conversions', folder: 'converters', icon: '\uD83D\uDD04', suf: '-converter' } };
  var defs = [];
  function T(id, name, cat, kw, blurb, def) { defs.push({ id: id, name: name, cat: cat, kw: kw, blurb: blurb, def: def }); }

  /* Group G: Text */
  T('word-counter', 'Word Counter', 'text', 'word counter, count words online', 'Count the words in your text instantly.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'Type or paste your text here.' }], calc: function (v) { return [['Words', words(v.t).length], ['Characters', String(v.t).length]]; } });
  T('character-counter', 'Character Counter', 'text', 'character counter, count characters online', 'Count characters with and without spaces.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'Hello world' }], calc: function (v) { var s = String(v.t); return [['Characters', s.length], ['Without spaces', s.replace(/\s/g, '').length]]; } });
  T('sentence-counter', 'Sentence Counter', 'text', 'sentence counter, count sentences', 'Count the number of sentences in your text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'Hello. How are you? I am fine!' }], calc: function (v) { return [['Sentences', sentences(v.t)], ['Words', words(v.t).length]]; } });
  T('paragraph-counter', 'Paragraph Counter', 'text', 'paragraph counter, count paragraphs', 'Count the paragraphs in your text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'Para one.\n\nPara two.' }], calc: function (v) { var p = String(v.t).split(/\n\s*\n/).filter(function (x) { return x.trim(); }); return [['Paragraphs', p.length], ['Words', words(v.t).length]]; } });
  T('case-converter', 'Case Converter', 'text', 'case converter, uppercase lowercase converter', 'Convert text between upper, lower and title case.', { inputs: [{ k: 't', label: 'Text', t: 'text', v: 'hello world' }, { k: 'mode', label: 'Convert to', t: 'sel', v: 'upper', opts: [opt('upper', 'UPPERCASE'), opt('lower', 'lowercase'), opt('title', 'Title Case'), opt('sentence', 'Sentence case')] }], calc: function (v) { var s = String(v.t), r; if (v.mode === 'upper') r = s.toUpperCase(); else if (v.mode === 'lower') r = s.toLowerCase(); else if (v.mode === 'title') r = s.toLowerCase().replace(/\b\w/g, function (c) { return c.toUpperCase(); }); else { r = s.toLowerCase(); r = r.charAt(0).toUpperCase() + r.slice(1); } return [['Result', r]]; } });
  T('reverse-words', 'Reverse Words', 'text', 'reverse words, reverse word order', 'Reverse the order of words in your text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'one two three' }], calc: function (v) { return [['Reversed', words(v.t).reverse().join(' ')]]; } });
  T('remove-extra-spaces', 'Remove Extra Spaces', 'text', 'remove extra spaces, trim spaces online', 'Collapse multiple spaces into single spaces.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'too    many     spaces' }], calc: function (v) { return [['Cleaned', String(v.t).replace(/\s+/g, ' ').trim()]]; } });
  T('remove-duplicate-lines', 'Remove Duplicate Lines', 'text', 'remove duplicate lines online', 'Remove duplicate lines from a list.', { inputs: [{ k: 't', label: 'Lines', t: 'ta', v: 'apple\nbanana\napple\ncherry' }], calc: function (v) { var seen = {}, out = []; String(v.t).split('\n').forEach(function (l) { if (!seen[l]) { seen[l] = 1; out.push(l); } }); return [['Unique lines', out.length], ['Result', out.join(' | ')]]; } });
  T('sort-lines', 'Sort Lines Alphabetically', 'text', 'sort lines alphabetically, alphabetize list', 'Sort lines of text in alphabetical order.', { inputs: [{ k: 't', label: 'Lines', t: 'ta', v: 'banana\napple\ncherry' }], calc: function (v) { return [['Sorted', String(v.t).split('\n').filter(function (x) { return x.trim(); }).sort().join(' | ')]]; } });
  T('find-and-replace', 'Find and Replace Text', 'text', 'find and replace text online', 'Find and replace all occurrences in text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'cat cat cat' }, { k: 'f', label: 'Find', t: 'text', v: 'cat' }, { k: 'r', label: 'Replace with', t: 'text', v: 'dog' }], calc: function (v) { var f = String(v.f); if (!f) return [['Result', String(v.t)]]; var parts = String(v.t).split(f); return [['Replacements', parts.length - 1], ['Result', parts.join(String(v.r))]]; } });
  T('text-similarity', 'Text Similarity Checker', 'text', 'text similarity checker, compare two texts', 'Compare two texts and get a similarity score.', { inputs: [{ k: 'a', label: 'Text A', t: 'ta', v: 'the quick brown fox' }, { k: 'b', label: 'Text B', t: 'ta', v: 'the slow brown dog' }], calc: function (v) { var A = words(v.a.toLowerCase()), B = words(v.b.toLowerCase()); var setB = {}; B.forEach(function (w) { setB[w] = 1; }); var inter = 0, uni = {}; A.concat(B).forEach(function (w) { uni[w] = 1; }); A.forEach(function (w) { if (setB[w]) inter++; }); var u = Object.keys(uni).length || 1; return [['Similarity', nf(inter / u * 100, 1) + '%']]; } });
  T('readability-score', 'Readability Score Checker', 'text', 'readability score checker, flesch reading ease', 'Get a readability score for your content.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'This is a simple sentence. It is easy to read.' }], calc: function (v) { var w = words(v.t).length, s = sentences(v.t) || 1; var avg = w / s; var score = mx(0, mn(100, rnd(120 - avg * 4))); return [['Words', w], ['Avg words/sentence', nf(avg, 1)], ['Readability', score + '/100']]; } });
  T('average-word-length', 'Average Word Length Calculator', 'text', 'average word length calculator', 'Find the average length of words in your text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'the quick brown fox jumps' }], calc: function (v) { var w = words(v.t); if (!w.length) return [['Average', 'Enter text']]; var total = w.reduce(function (s, x) { return s + x.length; }, 0); return [['Average length', nf(total / w.length, 2) + ' chars'], ['Words', w.length]]; } });
  T('unique-word-counter', 'Unique Word Counter', 'text', 'unique word counter, count unique words', 'Count the unique words in your text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'apple apple banana apple banana cherry' }], calc: function (v) { var seen = {}; words(v.t.toLowerCase()).forEach(function (w) { seen[w] = 1; }); return [['Unique words', Object.keys(seen).length], ['Total words', words(v.t).length]]; } });
  T('line-break-remover', 'Line Break Remover', 'text', 'line break remover, remove line breaks', 'Remove line breaks and join text into one line.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'line one\nline two\nline three' }], calc: function (v) { return [['Result', String(v.t).replace(/\s*\n\s*/g, ' ').trim()]]; } });
  T('character-occurrence', 'Character Occurrence Counter', 'text', 'character occurrence counter, count a character', 'Count how many times a character appears.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'mississippi' }, { k: 'c', label: 'Character', t: 'text', v: 's' }], calc: function (v) { var c = String(v.c).charAt(0); if (!c) return [['Count', 'Enter a character']]; var n = String(v.t).split(c).length - 1; return [['Occurrences', n]]; } });
  T('text-to-morse', 'Text to Morse Code Converter', 'text', 'text to morse code converter', 'Convert text into Morse code.', { inputs: [{ k: 't', label: 'Text', t: 'text', v: 'SOS' }], calc: function (v) { var out = String(v.t).toLowerCase().split('').map(function (c) { if (c === ' ') return '/'; return MORSE[c] || ''; }).filter(function (x) { return x; }).join(' '); return [['Morse code', out || '\u2014']]; } });
  T('morse-to-text', 'Morse Code to Text Converter', 'text', 'morse code to text converter, decode morse', 'Decode Morse code back into text.', { inputs: [{ k: 't', label: 'Morse code', t: 'text', v: '... --- ...' }], calc: function (v) { var out = String(v.t).trim().split(' ').map(function (m) { if (m === '/') return ' '; return MORSE_R[m] || ''; }).join(''); return [['Text', out.toUpperCase() || '\u2014']]; } });
  T('vowel-consonant-counter', 'Vowel and Consonant Counter', 'text', 'vowel consonant counter', 'Count vowels and consonants in your text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'Hello World' }], calc: function (v) { var s = String(v.t).toLowerCase(); var vo = (s.match(/[aeiou]/g) || []).length; var co = (s.match(/[bcdfghjklmnpqrstvwxyz]/g) || []).length; return [['Vowels', vo], ['Consonants', co]]; } });
  T('whitespace-counter', 'Whitespace Counter', 'text', 'whitespace counter, count spaces', 'Count spaces and whitespace characters in text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'a b  c   d' }], calc: function (v) { var s = String(v.t); return [['Spaces', (s.match(/ /g) || []).length], ['All whitespace', (s.match(/\s/g) || []).length]]; } });

  /* Group H: Converters */
  T('celsius-to-fahrenheit', 'Celsius to Fahrenheit Converter', 'conv', 'celsius to fahrenheit converter', 'Convert Celsius to Fahrenheit.', { inputs: [{ k: 'c', label: 'Celsius', v: 37, step: 'any' }], calc: function (v) { return [['Fahrenheit', nf(v.c * 9 / 5 + 32, 2) + ' \u00B0F']]; } });
  T('fahrenheit-to-celsius', 'Fahrenheit to Celsius Converter', 'conv', 'fahrenheit to celsius converter', 'Convert Fahrenheit to Celsius.', { inputs: [{ k: 'f', label: 'Fahrenheit', v: 98.6, step: 'any' }], calc: function (v) { return [['Celsius', nf((v.f - 32) * 5 / 9, 2) + ' \u00B0C']]; } });
  T('km-to-miles', 'Kilometers to Miles Converter', 'conv', 'km to miles converter, kilometers to miles', 'Convert kilometers to miles.', { inputs: [{ k: 'km', label: 'Kilometers', v: 10, step: 'any' }], calc: function (v) { return [['Miles', nf(v.km * 0.621371, 4) + ' mi']]; } });
  T('miles-to-km', 'Miles to Kilometers Converter', 'conv', 'miles to km converter, miles to kilometers', 'Convert miles to kilometers.', { inputs: [{ k: 'mi', label: 'Miles', v: 10, step: 'any' }], calc: function (v) { return [['Kilometers', nf(v.mi / 0.621371, 4) + ' km']]; } });
  T('kg-to-pounds', 'Kilograms to Pounds Converter', 'conv', 'kg to pounds converter, kilograms to pounds', 'Convert kilograms to pounds.', { inputs: [{ k: 'kg', label: 'Kilograms', v: 70, step: 'any' }], calc: function (v) { return [['Pounds', nf(v.kg * 2.20462, 3) + ' lb']]; } });
  T('pounds-to-kg', 'Pounds to Kilograms Converter', 'conv', 'pounds to kg converter, pounds to kilograms', 'Convert pounds to kilograms.', { inputs: [{ k: 'lb', label: 'Pounds', v: 150, step: 'any' }], calc: function (v) { return [['Kilograms', nf(v.lb / 2.20462, 3) + ' kg']]; } });
  T('cm-to-inches', 'Centimeters to Inches Converter', 'conv', 'cm to inches converter, centimeters to inches', 'Convert centimeters to inches.', { inputs: [{ k: 'cm', label: 'Centimeters', v: 180, step: 'any' }], calc: function (v) { return [['Inches', nf(v.cm / 2.54, 3) + ' in']]; } });
  T('inches-to-cm', 'Inches to Centimeters Converter', 'conv', 'inches to cm converter, inches to centimeters', 'Convert inches to centimeters.', { inputs: [{ k: 'in', label: 'Inches', v: 70, step: 'any' }], calc: function (v) { return [['Centimeters', nf(v['in'] * 2.54, 3) + ' cm']]; } });
  T('liters-to-gallons', 'Liters to Gallons Converter', 'conv', 'liters to gallons converter', 'Convert liters to US gallons.', { inputs: [{ k: 'l', label: 'Liters', v: 10, step: 'any' }], calc: function (v) { return [['US gallons', nf(v.l * 0.264172, 4) + ' gal']]; } });
  T('gallons-to-liters', 'Gallons to Liters Converter', 'conv', 'gallons to liters converter', 'Convert US gallons to liters.', { inputs: [{ k: 'g', label: 'US gallons', v: 5, step: 'any' }], calc: function (v) { return [['Liters', nf(v.g / 0.264172, 4) + ' L']]; } });
  T('sqft-to-sqm', 'Square Feet to Square Meters Converter', 'conv', 'square feet to square meters converter', 'Convert square feet to square meters.', { inputs: [{ k: 'sqft', label: 'Square feet', v: 1000, step: 'any' }], calc: function (v) { return [['Square meters', nf(v.sqft * 0.092903, 3) + ' m\u00B2']]; } });
  T('sqm-to-sqft', 'Square Meters to Square Feet Converter', 'conv', 'square meters to square feet converter', 'Convert square meters to square feet.', { inputs: [{ k: 'sqm', label: 'Square meters', v: 100, step: 'any' }], calc: function (v) { return [['Square feet', nf(v.sqm / 0.092903, 2) + ' sq ft']]; } });
  T('acres-to-hectares', 'Acres to Hectares Converter', 'conv', 'acres to hectares converter', 'Convert acres to hectares.', { inputs: [{ k: 'a', label: 'Acres', v: 5, step: 'any' }], calc: function (v) { return [['Hectares', nf(v.a * 0.404686, 4) + ' ha']]; } });
  T('mph-to-kmh', 'MPH to KMH Converter', 'conv', 'mph to kmh converter, miles per hour to kmph', 'Convert miles per hour to kilometers per hour.', { inputs: [{ k: 'mph', label: 'Miles per hour', v: 60, step: 'any' }], calc: function (v) { return [['km/h', nf(v.mph * 1.60934, 3) + ' km/h']]; } });
  T('kmh-to-mph', 'KMH to MPH Converter', 'conv', 'kmh to mph converter, kmph to miles per hour', 'Convert kilometers per hour to miles per hour.', { inputs: [{ k: 'kmh', label: 'Kilometers per hour', v: 100, step: 'any' }], calc: function (v) { return [['mph', nf(v.kmh / 1.60934, 3) + ' mph']]; } });
  T('bytes-to-mb', 'Bytes to Megabytes Converter', 'conv', 'bytes to mb converter', 'Convert bytes to megabytes.', { inputs: [{ k: 'b', label: 'Bytes', v: 1048576, step: 1 }], calc: function (v) { return [['Megabytes', nf(v.b / 1048576, 4) + ' MB'], ['Kilobytes', nf(v.b / 1024, 2) + ' KB']]; } });
  T('mb-to-gb', 'Megabytes to Gigabytes Converter', 'conv', 'mb to gb converter', 'Convert megabytes to gigabytes.', { inputs: [{ k: 'mb', label: 'Megabytes', v: 2048, step: 'any' }], calc: function (v) { return [['Gigabytes', nf(v.mb / 1024, 4) + ' GB']]; } });
  T('kb-to-mb', 'Kilobytes to Megabytes Converter', 'conv', 'kb to mb converter', 'Convert kilobytes to megabytes.', { inputs: [{ k: 'kb', label: 'Kilobytes', v: 2048, step: 'any' }], calc: function (v) { return [['Megabytes', nf(v.kb / 1024, 4) + ' MB']]; } });
  T('minutes-to-hours', 'Minutes to Hours Converter', 'conv', 'minutes to hours converter', 'Convert minutes to hours and minutes.', { inputs: [{ k: 'm', label: 'Minutes', v: 150, step: 1 }], calc: function (v) { return [['Hours', nf(v.m / 60, 3) + ' h'], ['H:M', fl(v.m / 60) + 'h ' + rnd(v.m % 60) + 'm']]; } });
  T('days-to-hours', 'Days to Hours Converter', 'conv', 'days to hours converter', 'Convert days to hours, minutes and seconds.', { inputs: [{ k: 'd', label: 'Days', v: 3, step: 'any' }], calc: function (v) { return [['Hours', nf(v.d * 24, 2) + ' h'], ['Minutes', nf(v.d * 1440, 0)], ['Seconds', nf(v.d * 86400, 0)]]; } });

  T('meters-to-feet', 'Meters to Feet Converter', 'conv', 'meters to feet converter', 'Convert meters to feet and inches.', { inputs: [{ k: 'm', label: 'Meters', v: 10, step: 'any' }], calc: function (v) { var ft = v.m * 3.28084; return [['Feet', nf(ft, 4) + ' ft'], ['Feet & inches', fl(ft) + "' " + rnd((ft - fl(ft)) * 12) + '"']]; } });
  T('feet-to-meters', 'Feet to Meters Converter', 'conv', 'feet to meters converter', 'Convert feet to meters.', { inputs: [{ k: 'ft', label: 'Feet', v: 30, step: 'any' }], calc: function (v) { return [['Meters', nf(v.ft / 3.28084, 4) + ' m']]; } });

  var metaArr = defs.map(function (d) { var c = CMAP[d.cat]; return { id: d.id, name: d.name, cat: d.cat, label: c.label, kw: d.kw, blurb: d.blurb, slug: d.id + c.suf, folder: c.folder, cslug: c.cslug, icon: c.icon }; });
  if (isNode) { module.exports = { meta: metaArr, defs: defs, CMAP: CMAP }; return; }
  var CS = root.CS, SEO = root.SEO;
  if (!CS || !CS.Calc) return;
  defs.forEach(function (d) { var c = CMAP[d.cat]; if (CS.Calc.get && CS.Calc.get(d.id)) return; CS.Calc.register({ id: d.id, name: d.name, category: c.label, icon: c.icon, description: d.blurb, render: simple(d.def) }); });
  if (SEO && SEO.TOOLS) { defs.forEach(function (d) { var c = CMAP[d.cat]; if (!SEO.TOOLS[d.id]) { SEO.TOOLS[d.id] = { slug: d.id + c.suf, cat: c.cslug, icon: c.icon, name: d.name, title: d.name + ' | allfreecalculators.in', desc: d.blurb, keywords: d.kw, intro: d.blurb, options: [], faqs: [{ q: 'Is the ' + d.name + ' free?', a: 'Yes, it is 100% free with no sign-up.' }, { q: 'Does it work on mobile?', a: 'Yes, on any device in your browser.' }], related: [] }; if (SEO.ORDER && SEO.ORDER.indexOf(d.id) < 0) SEO.ORDER.push(d.id); } }); }
})(typeof self !== 'undefined' ? self : this);
