/* allfreecalculators.in - group E (Business / Marketing / SEO, 25). Self-contained. */
(function (root) {
  'use strict';
  var isNode = (typeof module !== 'undefined' && module.exports);
  var pw = Math.pow, rt = Math.sqrt, mx = Math.max, mn = Math.min, rnd = Math.round, fl = Math.floor;
  function nf(n, d) { d = d == null ? 2 : d; return isFinite(n) ? Number(n).toLocaleString('en-IN', { maximumFractionDigits: d }) : '\u2014'; }
  function money(n) { return isFinite(n) ? '\u20B9' + Number(n).toLocaleString('en-IN', { maximumFractionDigits: 0 }) : '\u2014'; }
  function pct(n) { return isFinite(n) ? nf(n, 2) + '%' : '\u2014'; }
  function opt(v, l) { return { value: v, label: l }; }
  function words(s) { s = String(s || '').trim(); return s ? s.split(/\s+/) : []; }
  function sentences(s) { var a = String(s || '').split(/[.!?]+/).filter(function (x) { return x.trim(); }); return a.length; }
  function simple(def) { return function () { var el = CS.el, wrap = el('div', { class: 'simplecalc' }); var grid = el('div', { class: 'cs-grid' }), inputs = {}; def.inputs.forEach(function (f) { var node; if (f.t === 'sel') node = CS.selectInput(f.opts, { value: f.v, onchange: run }); else if (f.t === 'ta') { node = el('textarea', { rows: f.rows || 5, style: 'width:100%;min-height:110px' }); node.value = f.v != null ? f.v : ''; node.addEventListener('input', run); } else if (f.t === 'date' || f.t === 'time' || f.t === 'text') { node = el('input', { type: f.t, value: f.v != null ? f.v : '' }); node.addEventListener('input', run); node.addEventListener('change', run); } else node = CS.numInput({ value: f.v, step: f.step, oninput: run }); inputs[f.k] = node; grid.appendChild(CS.field(f.label, node, f.hint)); }); var res = el('div', { class: 'result-area' }); wrap.appendChild(grid); wrap.appendChild(res); function readv() { var o = {}; def.inputs.forEach(function (f) { var n = inputs[f.k]; o[f.k] = (f.t === 'sel' || f.t === 'date' || f.t === 'time' || f.t === 'text' || f.t === 'ta') ? n.value : parseFloat(n.value); }); return o; } function run() { var out; try { out = def.calc(readv()); } catch (e) { out = [['Error', 'Check your inputs']]; } res.innerHTML = ''; if (!out || !out.length) return; var row = el('div', { class: 'kpi-row' }); out.forEach(function (p) { row.appendChild(CS.kpi(p[0], p[1], { class: p[2] || '' })); }); res.appendChild(row); } setTimeout(run, 0); return wrap; }; }
  var CMAP = { mkt: { label: 'Marketing', cslug: 'business', folder: 'business', icon: '\uD83D\uDCE3', suf: '-calculator' }, biz: { label: 'Business', cslug: 'business', folder: 'business', icon: '\uD83D\uDCBC', suf: '-calculator' }, seo: { label: 'SEO', cslug: 'seo-tools', folder: 'seo', icon: '\uD83D\uDD0E', suf: '-tool' } };
  var defs = [];
  function T(id, name, cat, kw, blurb, def) { defs.push({ id: id, name: name, cat: cat, kw: kw, blurb: blurb, def: def }); }

  T('cpc', 'CPC Calculator', 'mkt', 'cpc calculator, cost per click', 'Calculate the cost per click of an ad campaign.', { inputs: [{ k: 'cost', label: 'Total ad cost', v: 5000, step: 'any' }, { k: 'clicks', label: 'Clicks', v: 500, step: 1 }], calc: function (v) { return [['CPC', money(v.cost / v.clicks)]]; } });
  T('cpm', 'CPM Calculator', 'mkt', 'cpm calculator, cost per mille', 'Calculate the cost per 1,000 impressions.', { inputs: [{ k: 'cost', label: 'Total ad cost', v: 5000, step: 'any' }, { k: 'imp', label: 'Impressions', v: 100000, step: 1 }], calc: function (v) { return [['CPM', money(v.cost / v.imp * 1000)]]; } });
  T('ctr', 'CTR Calculator', 'mkt', 'ctr calculator, click through rate', 'Calculate the click-through rate of your ads.', { inputs: [{ k: 'clicks', label: 'Clicks', v: 500, step: 1 }, { k: 'imp', label: 'Impressions', v: 25000, step: 1 }], calc: function (v) { return [['CTR', pct(v.clicks / v.imp * 100)]]; } });
  T('roas', 'ROAS Calculator', 'mkt', 'roas calculator, return on ad spend', 'Calculate the return on ad spend.', { inputs: [{ k: 'rev', label: 'Revenue from ads', v: 50000, step: 'any' }, { k: 'spend', label: 'Ad spend', v: 10000, step: 'any' }], calc: function (v) { return [['ROAS', nf(v.rev / v.spend, 2) + 'x'], ['Return', pct((v.rev / v.spend - 1) * 100)]]; } });
  T('conversion-rate', 'Conversion Rate Calculator', 'mkt', 'conversion rate calculator', 'Calculate your conversion rate.', { inputs: [{ k: 'conv', label: 'Conversions', v: 50, step: 1 }, { k: 'visits', label: 'Visitors', v: 2000, step: 1 }], calc: function (v) { return [['Conversion rate', pct(v.conv / v.visits * 100)]]; } });
  T('customer-ltv', 'Customer Lifetime Value Calculator', 'biz', 'customer lifetime value calculator, ltv', 'Estimate the lifetime value of a customer.', { inputs: [{ k: 'val', label: 'Avg purchase value', v: 1000, step: 'any' }, { k: 'freq', label: 'Purchases per year', v: 4, step: 'any' }, { k: 'yrs', label: 'Customer lifespan (years)', v: 3, step: 'any' }], calc: function (v) { return [['Lifetime value', money(v.val * v.freq * v.yrs)], ['Yearly value', money(v.val * v.freq)]]; } });
  T('cac', 'Customer Acquisition Cost Calculator', 'biz', 'customer acquisition cost calculator, cac', 'Calculate the cost to acquire one customer.', { inputs: [{ k: 'spend', label: 'Sales + marketing spend', v: 100000, step: 'any' }, { k: 'cust', label: 'New customers', v: 200, step: 1 }], calc: function (v) { return [['CAC', money(v.spend / v.cust)]]; } });
  T('churn-rate', 'Churn Rate Calculator', 'biz', 'churn rate calculator, customer churn', 'Calculate the customer churn rate.', { inputs: [{ k: 'lost', label: 'Customers lost', v: 20, step: 1 }, { k: 'start', label: 'Customers at start', v: 500, step: 1 }], calc: function (v) { return [['Churn rate', pct(v.lost / v.start * 100)], ['Retention rate', pct((1 - v.lost / v.start) * 100)]]; } });
  T('email-open-rate', 'Email Open Rate Calculator', 'mkt', 'email open rate calculator', 'Calculate your email open and click rates.', { inputs: [{ k: 'opens', label: 'Emails opened', v: 800, step: 1 }, { k: 'del', label: 'Emails delivered', v: 4000, step: 1 }], calc: function (v) { return [['Open rate', pct(v.opens / v.del * 100)]]; } });
  T('youtube-revenue', 'YouTube Revenue Calculator', 'mkt', 'youtube revenue calculator, youtube earnings', 'Estimate YouTube earnings from views and RPM.', { inputs: [{ k: 'views', label: 'Monthly views', v: 100000, step: 1 }, { k: 'rpm', label: 'RPM (per 1000 views)', v: 80, step: 'any' }], calc: function (v) { return [['Monthly earnings', money(v.views / 1000 * v.rpm)], ['Yearly earnings', money(v.views / 1000 * v.rpm * 12)]]; } });
  T('adsense-revenue', 'AdSense Revenue Calculator', 'mkt', 'adsense revenue calculator, adsense earnings', 'Estimate AdSense earnings from traffic.', { inputs: [{ k: 'pv', label: 'Monthly pageviews', v: 100000, step: 1 }, { k: 'ctr', label: 'CTR (%)', v: 1.5, step: 'any' }, { k: 'cpc', label: 'Avg CPC', v: 15, step: 'any' }], calc: function (v) { var clicks = v.pv * v.ctr / 100; return [['Monthly earnings', money(clicks * v.cpc)], ['Clicks/month', nf(clicks, 0)]]; } });
  T('instagram-engagement', 'Instagram Engagement Rate Calculator', 'mkt', 'instagram engagement rate calculator', 'Calculate your Instagram engagement rate.', { inputs: [{ k: 'inter', label: 'Likes + comments', v: 500, step: 1 }, { k: 'foll', label: 'Followers', v: 10000, step: 1 }], calc: function (v) { return [['Engagement rate', pct(v.inter / v.foll * 100)]]; } });
  T('influencer-rate', 'Influencer Rate Calculator', 'mkt', 'influencer rate calculator, sponsored post price', 'Estimate a fair sponsored-post rate.', { inputs: [{ k: 'foll', label: 'Followers', v: 50000, step: 1 }, { k: 'eng', label: 'Engagement rate (%)', v: 3, step: 'any' }], calc: function (v) { var base = v.foll / 100 * (1 + v.eng / 10); return [['Suggested rate', money(base)], ['Range', money(base * 0.7) + ' - ' + money(base * 1.3)]]; } });
  T('profit-margin', 'Profit Margin Calculator', 'biz', 'profit margin calculator, net margin', 'Calculate profit and profit margin.', { inputs: [{ k: 'rev', label: 'Revenue', v: 100000, step: 'any' }, { k: 'cost', label: 'Total cost', v: 70000, step: 'any' }], calc: function (v) { return [['Profit', money(v.rev - v.cost)], ['Margin', pct((v.rev - v.cost) / v.rev * 100)]]; } });
  T('gross-margin', 'Gross Margin Calculator', 'biz', 'gross margin calculator, gross profit margin', 'Calculate gross profit and gross margin.', { inputs: [{ k: 'rev', label: 'Revenue', v: 100000, step: 'any' }, { k: 'cogs', label: 'Cost of goods sold', v: 60000, step: 'any' }], calc: function (v) { return [['Gross profit', money(v.rev - v.cogs)], ['Gross margin', pct((v.rev - v.cogs) / v.rev * 100)]]; } });
  T('wholesale-price', 'Wholesale Price Calculator', 'biz', 'wholesale price calculator, markup price', 'Find the selling price from cost and markup.', { inputs: [{ k: 'cost', label: 'Cost price', v: 500, step: 'any' }, { k: 'markup', label: 'Markup (%)', v: 40, step: 'any' }], calc: function (v) { return [['Selling price', money(v.cost * (1 + v.markup / 100))], ['Profit', money(v.cost * v.markup / 100)]]; } });
  T('eoq', 'Economic Order Quantity Calculator', 'biz', 'economic order quantity calculator, eoq', 'Calculate the economic order quantity.', { inputs: [{ k: 'd', label: 'Annual demand (units)', v: 10000, step: 1 }, { k: 'o', label: 'Order cost', v: 500, step: 'any' }, { k: 'h', label: 'Holding cost per unit', v: 20, step: 'any' }], calc: function (v) { return [['EOQ', nf(rt(2 * v.d * v.o / v.h), 0) + ' units'], ['Orders per year', nf(v.d / rt(2 * v.d * v.o / v.h), 1)]]; } });
  T('depreciation', 'Straight Line Depreciation Calculator', 'biz', 'straight line depreciation calculator', 'Calculate annual straight-line depreciation.', { inputs: [{ k: 'cost', label: 'Asset cost', v: 100000, step: 'any' }, { k: 'sal', label: 'Salvage value', v: 10000, step: 'any' }, { k: 'life', label: 'Useful life (years)', v: 5, step: 1 }], calc: function (v) { return [['Annual depreciation', money((v.cost - v.sal) / v.life)], ['Depreciable amount', money(v.cost - v.sal)]]; } });
  T('payback-period', 'Payback Period Calculator', 'biz', 'payback period calculator', 'Find how long it takes to recover an investment.', { inputs: [{ k: 'inv', label: 'Initial investment', v: 500000, step: 'any' }, { k: 'cf', label: 'Annual cash flow', v: 120000, step: 'any' }], calc: function (v) { var y = v.inv / v.cf; return [['Payback period', nf(y, 2) + ' years'], ['Months', nf(y * 12, 0)]]; } });
  T('npv', 'NPV Calculator', 'biz', 'npv calculator, net present value', 'Calculate the net present value of cash flows.', { inputs: [{ k: 'init', label: 'Initial investment', v: 500000, step: 'any' }, { k: 'cf', label: 'Annual cash flow', v: 150000, step: 'any' }, { k: 'r', label: 'Discount rate (%)', v: 10, step: 'any' }, { k: 'n', label: 'Years', v: 5, step: 1 }], calc: function (v) { var npv = -v.init, i = v.r / 100; for (var t = 1; t <= v.n; t++) npv += v.cf / pw(1 + i, t); return [['NPV', money(npv)], ['Verdict', npv >= 0 ? 'Profitable' : 'Not profitable']]; } });
  T('markup-margin', 'Markup to Margin Converter', 'biz', 'markup to margin calculator, convert markup margin', 'Convert a markup percentage into a profit margin.', { inputs: [{ k: 'markup', label: 'Markup (%)', v: 50, step: 'any' }], calc: function (v) { return [['Profit margin', pct(v.markup / (100 + v.markup) * 100)]]; } });
  T('working-capital', 'Working Capital Calculator', 'biz', 'working capital calculator, current ratio', 'Calculate working capital and current ratio.', { inputs: [{ k: 'ca', label: 'Current assets', v: 500000, step: 'any' }, { k: 'cl', label: 'Current liabilities', v: 300000, step: 'any' }], calc: function (v) { return [['Working capital', money(v.ca - v.cl)], ['Current ratio', nf(v.ca / v.cl, 2)]]; } });
  T('keyword-density', 'Keyword Density Checker', 'seo', 'keyword density checker, keyword density tool', 'Check how often a keyword appears in your text.', { inputs: [{ k: 'text', label: 'Your content', t: 'ta', v: 'Notion AI is a helpful AI assistant. This AI can write and plan.' }, { k: 'kw', label: 'Keyword', t: 'text', v: 'ai' }], calc: function (v) { var w = words(v.text), total = w.length; var kw = String(v.kw || '').toLowerCase().trim(); if (!total || !kw) return [['Density', 'Enter text and keyword']]; var c = w.filter(function (x) { return x.toLowerCase().replace(/[^a-z0-9]/g, '') === kw; }).length; return [['Total words', total], ['Keyword count', c], ['Density', pct(c / total * 100)]]; } });
  T('meta-tag-length', 'Meta Tag Length Checker', 'seo', 'meta tag length checker, meta title description length', 'Check if your title and meta description fit Google limits.', { inputs: [{ k: 'title', label: 'Meta title', t: 'text', v: 'Free Online Calculator Tools' }, { k: 'desc', label: 'Meta description', t: 'ta', v: 'Use our free online calculators for finance, health, math and more.' }], calc: function (v) { var tl = String(v.title || '').length, dl = String(v.desc || '').length; return [['Title length', tl + ' (' + (tl >= 30 && tl <= 60 ? 'Good' : 'Adjust') + ')'], ['Description length', dl + ' (' + (dl >= 120 && dl <= 160 ? 'Good' : 'Adjust') + ')']]; } });
  T('seo-content-score', 'SEO Content Score Checker', 'seo', 'seo content score checker, content readability', 'Get a quick SEO readability score for your content.', { inputs: [{ k: 'text', label: 'Your content', t: 'ta', v: 'Write clear and helpful content. Short sentences rank better. Use your keyword naturally.' }], calc: function (v) { var w = words(v.text), s = sentences(v.text) || 1; var avg = w.length / s; var score = mx(0, mn(100, rnd(100 - (avg - 15) * 3))); return [['Word count', w.length], ['Sentences', s], ['Avg words/sentence', nf(avg, 1)], ['Readability score', score + '/100']]; } });

  var metaArr = defs.map(function (d) { var c = CMAP[d.cat]; return { id: d.id, name: d.name, cat: d.cat, label: c.label, kw: d.kw, blurb: d.blurb, slug: d.id + c.suf, folder: c.folder, cslug: c.cslug, icon: c.icon }; });
  if (isNode) { module.exports = { meta: metaArr, defs: defs, CMAP: CMAP }; return; }
  var CS = root.CS, SEO = root.SEO;
  if (!CS || !CS.Calc) return;
  defs.forEach(function (d) { var c = CMAP[d.cat]; if (CS.Calc.get && CS.Calc.get(d.id)) return; CS.Calc.register({ id: d.id, name: d.name, category: c.label, icon: c.icon, description: d.blurb, render: simple(d.def) }); });
  if (SEO && SEO.TOOLS) { defs.forEach(function (d) { var c = CMAP[d.cat]; if (!SEO.TOOLS[d.id]) { SEO.TOOLS[d.id] = { slug: d.id + c.suf, cat: c.cslug, icon: c.icon, name: d.name, title: d.name + ' | allfreecalculators.in', desc: d.blurb, keywords: d.kw, intro: d.blurb, options: [], faqs: [{ q: 'Is the ' + d.name + ' free?', a: 'Yes, it is 100% free with no sign-up.' }, { q: 'Does it work on mobile?', a: 'Yes, on any device in your browser.' }], related: [] }; if (SEO.ORDER && SEO.ORDER.indexOf(d.id) < 0) SEO.ORDER.push(d.id); } }); }
})(typeof self !== 'undefined' ? self : this);
