/* allfreecalculators.in - group F (Developer / Utilities, 25). Self-contained. */
(function (root) {
  'use strict';
  var isNode = (typeof module !== 'undefined' && module.exports);
  var fl = Math.floor, rnd = Math.round, ab = Math.abs;
  function nf(n, d) { d = d == null ? 2 : d; return isFinite(n) ? Number(n).toLocaleString('en-IN', { maximumFractionDigits: d }) : '\u2014'; }
  function opt(v, l) { return { value: v, label: l }; }
  function gcd(a, b) { a = ab(fl(a)); b = ab(fl(b)); while (b) { var t = b; b = a % b; a = t; } return a || 1; }
  function uuid() { return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) { var r = Math.random() * 16 | 0, val = c === 'x' ? r : (r & 0x3 | 0x8); return val.toString(16); }); }
  function slugify(s) { return String(s || '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }
  function b64enc(s) { try { return (typeof btoa !== 'undefined') ? btoa(unescape(encodeURIComponent(s))) : Buffer.from(String(s), 'utf8').toString('base64'); } catch (e) { return '\u2014'; } }
  function b64dec(s) { try { return (typeof atob !== 'undefined') ? decodeURIComponent(escape(atob(s))) : Buffer.from(String(s), 'base64').toString('utf8'); } catch (e) { return 'Invalid input'; } }
  var LOREM = 'lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamco laboris nisi aliquip ex ea commodo consequat'.split(' ');
  function simple(def) { return function () { var el = CS.el, wrap = el('div', { class: 'simplecalc' }); var grid = el('div', { class: 'cs-grid' }), inputs = {}; def.inputs.forEach(function (f) { var node; if (f.t === 'sel') node = CS.selectInput(f.opts, { value: f.v, onchange: run }); else if (f.t === 'ta') { node = el('textarea', { rows: f.rows || 5, style: 'width:100%;min-height:110px' }); node.value = f.v != null ? f.v : ''; node.addEventListener('input', run); } else if (f.t === 'date' || f.t === 'time' || f.t === 'text') { node = el('input', { type: f.t, value: f.v != null ? f.v : '' }); node.addEventListener('input', run); node.addEventListener('change', run); } else node = CS.numInput({ value: f.v, step: f.step, oninput: run }); inputs[f.k] = node; grid.appendChild(CS.field(f.label, node, f.hint)); }); var res = el('div', { class: 'result-area' }); wrap.appendChild(grid); wrap.appendChild(res); function readv() { var o = {}; def.inputs.forEach(function (f) { var n = inputs[f.k]; o[f.k] = (f.t === 'sel' || f.t === 'date' || f.t === 'time' || f.t === 'text' || f.t === 'ta') ? n.value : parseFloat(n.value); }); return o; } function run() { var out; try { out = def.calc(readv()); } catch (e) { out = [['Error', 'Check your inputs']]; } res.innerHTML = ''; if (!out || !out.length) return; var row = el('div', { class: 'kpi-row' }); out.forEach(function (p) { row.appendChild(CS.kpi(p[0], p[1], { class: p[2] || '' })); }); res.appendChild(row); } setTimeout(run, 0); return wrap; }; }
  var CMAP = { dev: { label: 'Developer', cslug: 'web-developer-tools', folder: 'utilities', icon: '\uD83D\uDCBB', suf: '-tool' } };
  var defs = [];
  function T(id, name, kw, blurb, def) { defs.push({ id: id, name: name, cat: 'dev', kw: kw, blurb: blurb, def: def }); }

  T('base64-encode', 'Base64 Encode', 'base64 encode, text to base64', 'Encode text to Base64 online.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'Hello World' }], calc: function (v) { return [['Base64', b64enc(v.t)]]; } });
  T('base64-decode', 'Base64 Decode', 'base64 decode, base64 to text', 'Decode Base64 back to text online.', { inputs: [{ k: 't', label: 'Base64', t: 'ta', v: 'SGVsbG8gV29ybGQ=' }], calc: function (v) { return [['Decoded text', b64dec(v.t)]]; } });
  T('url-encode', 'URL Encode', 'url encode, percent encoding', 'URL-encode text safely.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'hello world & friends' }], calc: function (v) { return [['Encoded', encodeURIComponent(v.t)]]; } });
  T('url-decode', 'URL Decode', 'url decode, decode percent encoding', 'Decode a URL-encoded string.', { inputs: [{ k: 't', label: 'Encoded text', t: 'ta', v: 'hello%20world%20%26%20friends' }], calc: function (v) { try { return [['Decoded', decodeURIComponent(v.t)]]; } catch (e) { return [['Decoded', 'Invalid input']]; } } });
  T('binary-to-decimal', 'Binary to Decimal Converter', 'binary to decimal converter', 'Convert a binary number to decimal.', { inputs: [{ k: 't', label: 'Binary', t: 'text', v: '101010' }], calc: function (v) { var n = parseInt(String(v.t).trim(), 2); return [['Decimal', isFinite(n) ? n : 'Invalid binary']]; } });
  T('decimal-to-binary', 'Decimal to Binary Converter', 'decimal to binary converter', 'Convert a decimal number to binary.', { inputs: [{ k: 'n', label: 'Decimal', v: 42, step: 1 }], calc: function (v) { return [['Binary', fl(ab(v.n)).toString(2)]]; } });
  T('decimal-to-hex', 'Decimal to Hex Converter', 'decimal to hex converter, decimal to hexadecimal', 'Convert a decimal number to hexadecimal.', { inputs: [{ k: 'n', label: 'Decimal', v: 255, step: 1 }], calc: function (v) { return [['Hex', fl(ab(v.n)).toString(16).toUpperCase()]]; } });
  T('hex-to-decimal', 'Hex to Decimal Converter', 'hex to decimal converter, hexadecimal to decimal', 'Convert a hexadecimal number to decimal.', { inputs: [{ k: 't', label: 'Hex', t: 'text', v: 'FF' }], calc: function (v) { var n = parseInt(String(v.t).replace(/^0x/i, '').trim(), 16); return [['Decimal', isFinite(n) ? n : 'Invalid hex']]; } });
  T('text-to-binary', 'Text to Binary Converter', 'text to binary converter, ascii to binary', 'Convert text to its binary representation.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'Hi' }], calc: function (v) { var out = String(v.t).split('').map(function (c) { var b = c.charCodeAt(0).toString(2); while (b.length < 8) b = '0' + b; return b; }).join(' '); return [['Binary', out || '\u2014']]; } });
  T('uuid-generator', 'UUID Generator', 'uuid generator, guid generator', 'Generate a random UUID (v4).', { inputs: [{ k: 'n', label: 'How many', v: 1, step: 1 }], calc: function (v) { var a = []; for (var i = 0; i < Math.max(1, Math.min(10, v.n)); i++) a.push(uuid()); return [['UUID', a.join('  ')]]; } });
  T('px-to-rem', 'PX to REM Converter', 'px to rem converter', 'Convert pixels to rem units.', { inputs: [{ k: 'px', label: 'Pixels', v: 24, step: 'any' }, { k: 'base', label: 'Base font size (px)', v: 16, step: 'any' }], calc: function (v) { return [['REM', nf(v.px / v.base, 4) + ' rem']]; } });
  T('rem-to-px', 'REM to PX Converter', 'rem to px converter', 'Convert rem units to pixels.', { inputs: [{ k: 'rem', label: 'REM', v: 1.5, step: 'any' }, { k: 'base', label: 'Base font size (px)', v: 16, step: 'any' }], calc: function (v) { return [['Pixels', nf(v.rem * v.base, 2) + ' px']]; } });
  T('aspect-ratio', 'Aspect Ratio Calculator', 'aspect ratio calculator', 'Find the simplest aspect ratio of a size.', { inputs: [{ k: 'w', label: 'Width', v: 1920, step: 1 }, { k: 'h', label: 'Height', v: 1080, step: 1 }], calc: function (v) { var g = gcd(v.w, v.h); return [['Aspect ratio', (v.w / g) + ':' + (v.h / g)], ['Decimal', nf(v.w / v.h, 3)]]; } });
  T('hex-to-rgb', 'HEX to RGB Converter', 'hex to rgb converter, hex color to rgb', 'Convert a HEX color to RGB.', { inputs: [{ k: 't', label: 'HEX color', t: 'text', v: '#3498db' }], calc: function (v) { var h = String(v.t).replace('#', ''); if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2]; var n = parseInt(h, 16); if (h.length !== 6 || !isFinite(n)) return [['RGB', 'Invalid HEX']]; return [['RGB', 'rgb(' + ((n >> 16) & 255) + ', ' + ((n >> 8) & 255) + ', ' + (n & 255) + ')']]; } });
  T('rgb-to-hex', 'RGB to HEX Converter', 'rgb to hex converter, rgb color to hex', 'Convert RGB values to a HEX color.', { inputs: [{ k: 'r', label: 'Red (0-255)', v: 52, step: 1 }, { k: 'g', label: 'Green (0-255)', v: 152, step: 1 }, { k: 'b', label: 'Blue (0-255)', v: 219, step: 1 }], calc: function (v) { function h(x) { x = Math.max(0, Math.min(255, fl(x))).toString(16); return x.length < 2 ? '0' + x : x; } return [['HEX', ('#' + h(v.r) + h(v.g) + h(v.b)).toUpperCase()]]; } });
  T('slug-generator', 'Slug Generator', 'slug generator, url slug maker', 'Turn any title into a clean URL slug.', { inputs: [{ k: 't', label: 'Title', t: 'text', v: 'My Awesome Blog Post!' }], calc: function (v) { return [['Slug', slugify(v.t) || '\u2014']]; } });
  T('lorem-ipsum', 'Lorem Ipsum Generator', 'lorem ipsum generator, dummy text generator', 'Generate placeholder Lorem Ipsum text.', { inputs: [{ k: 'n', label: 'Number of words', v: 30, step: 1 }], calc: function (v) { var out = [], c = Math.max(1, Math.min(500, fl(v.n))); for (var i = 0; i < c; i++) out.push(LOREM[i % LOREM.length]); var s = out.join(' '); return [['Lorem Ipsum', s.charAt(0).toUpperCase() + s.slice(1) + '.']]; } });
  T('timestamp-to-date', 'Timestamp to Date Converter', 'timestamp to date converter, unix timestamp', 'Convert a Unix timestamp to a readable date.', { inputs: [{ k: 'ts', label: 'Unix timestamp', v: 1700000000, step: 1 }], calc: function (v) { var ms = v.ts < 1e12 ? v.ts * 1000 : v.ts; var d = new Date(ms); return [['UTC date', d.toUTCString()], ['ISO', d.toISOString()]]; } });
  T('date-to-timestamp', 'Date to Timestamp Converter', 'date to timestamp converter, date to unix', 'Convert a date to a Unix timestamp.', { inputs: [{ k: 'd', label: 'Date', t: 'date', v: '2024-01-01' }], calc: function (v) { var d = new Date(v.d); if (isNaN(d.getTime())) return [['Timestamp', 'Enter a valid date']]; return [['Unix (seconds)', fl(d.getTime() / 1000)], ['Milliseconds', d.getTime()]]; } });
  T('text-repeater', 'Text Repeater', 'text repeater, repeat text online', 'Repeat any text a number of times.', { inputs: [{ k: 't', label: 'Text', t: 'text', v: 'ha' }, { k: 'n', label: 'Times', v: 5, step: 1 }], calc: function (v) { var c = Math.max(1, Math.min(1000, fl(v.n))); return [['Result', new Array(c + 1).join(String(v.t))]]; } });
  T('reverse-string', 'Reverse String', 'reverse string, reverse text online', 'Reverse any string of text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'Hello World' }], calc: function (v) { return [['Reversed', String(v.t).split('').reverse().join('')]]; } });
  T('remove-spaces', 'Remove Spaces', 'remove spaces, delete whitespace online', 'Remove all spaces and whitespace from text.', { inputs: [{ k: 't', label: 'Text', t: 'ta', v: 'h e l l o' }], calc: function (v) { return [['No spaces', String(v.t).replace(/\s+/g, '')]]; } });
  T('random-password', 'Random Password Generator', 'random password generator, strong password', 'Generate a strong random password.', { inputs: [{ k: 'len', label: 'Length', v: 16, step: 1 }, { k: 'sym', label: 'Include symbols', t: 'sel', v: 'yes', opts: [opt('yes', 'Yes'), opt('no', 'No')] }], calc: function (v) { var cs = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789' + (v.sym === 'yes' ? '!@#$%^&*()-_=+' : ''); var len = Math.max(4, Math.min(64, fl(v.len))), p = ''; for (var i = 0; i < len; i++) p += cs.charAt(fl(Math.random() * cs.length)); return [['Password', p]]; } });
  T('octal-to-decimal', 'Octal to Decimal Converter', 'octal to decimal converter', 'Convert an octal number to decimal.', { inputs: [{ k: 't', label: 'Octal', t: 'text', v: '52' }], calc: function (v) { var n = parseInt(String(v.t).trim(), 8); return [['Decimal', isFinite(n) ? n : 'Invalid octal']]; } });
  T('decimal-to-octal', 'Decimal to Octal Converter', 'decimal to octal converter', 'Convert a decimal number to octal.', { inputs: [{ k: 'n', label: 'Decimal', v: 42, step: 1 }], calc: function (v) { return [['Octal', fl(ab(v.n)).toString(8)]]; } });

  var metaArr = defs.map(function (d) { var c = CMAP[d.cat]; return { id: d.id, name: d.name, cat: d.cat, label: c.label, kw: d.kw, blurb: d.blurb, slug: d.id + c.suf, folder: c.folder, cslug: c.cslug, icon: c.icon }; });
  if (isNode) { module.exports = { meta: metaArr, defs: defs, CMAP: CMAP }; return; }
  var CS = root.CS, SEO = root.SEO;
  if (!CS || !CS.Calc) return;
  defs.forEach(function (d) { var c = CMAP[d.cat]; if (CS.Calc.get && CS.Calc.get(d.id)) return; CS.Calc.register({ id: d.id, name: d.name, category: c.label, icon: c.icon, description: d.blurb, render: simple(d.def) }); });
  if (SEO && SEO.TOOLS) { defs.forEach(function (d) { var c = CMAP[d.cat]; if (!SEO.TOOLS[d.id]) { SEO.TOOLS[d.id] = { slug: d.id + c.suf, cat: c.cslug, icon: c.icon, name: d.name, title: d.name + ' | allfreecalculators.in', desc: d.blurb, keywords: d.kw, intro: d.blurb, options: [], faqs: [{ q: 'Is the ' + d.name + ' free?', a: 'Yes, it is 100% free with no sign-up.' }, { q: 'Does it work on mobile?', a: 'Yes, on any device in your browser.' }], related: [] }; if (SEO.ORDER && SEO.ORDER.indexOf(d.id) < 0) SEO.ORDER.push(d.id); } }); }
})(typeof self !== 'undefined' ? self : this);
