/* allfreecalculators.in - 40 additional working tools (low-competition long-tail keywords).
   Registered into the same runtime engine + SEO registry as tools-300.js.
   Contract: CS.Calc.register({id,name,category,icon,description,render:simple(def)}) */
(function (root) {
  'use strict';
  var CS = root.CS;
  var SEO = (typeof module !== 'undefined' && module.exports) ? require('./seo-data.js') : root.SEO;
  if (!SEO) return;

  function fnum(n, d) { return isFinite(n) ? (CS ? CS.fmtNum(n, d == null ? 2 : d) : Number(n).toFixed(d == null ? 2 : d)) : '\u2014'; }
  function fmoney(n) { return isFinite(n) ? (CS ? CS.fmtMoney(n) : '\u20B9' + Number(n).toFixed(2)) : '\u2014'; }
  function opt(v, l) { return { value: v, label: l }; }
  function LIST(s) { return String(s || '').split(/[^0-9.\-]+/).map(parseFloat).filter(function (x) { return isFinite(x); }); }
  function pdate(s) { var d = new Date(s); return isNaN(d.getTime()) ? null : d; }
  function gcd(a, b) { a = Math.abs(a); b = Math.abs(b); while (b) { var t = b; b = a % b; a = t; } return a; }

  function simple(def) {
    return function () {
      var el = CS.el, wrap = el('div', { class: 'simplecalc' });
      var grid = el('div', { class: 'cs-grid' }), inputs = {};
      def.inputs.forEach(function (f) {
        var node;
        if (f.t === 'sel') node = CS.selectInput(f.opts, { value: f.v, onchange: run });
        else if (f.t === 'date' || f.t === 'time' || f.t === 'text') { node = el('input', { type: f.t, value: f.v != null ? f.v : '' }); node.addEventListener('input', run); node.addEventListener('change', run); }
        else node = CS.numInput({ value: f.v, step: f.step, oninput: run });
        inputs[f.k] = node;
        grid.appendChild(CS.field(f.label, node, f.hint));
      });
      var res = el('div', { class: 'result-area' });
      wrap.appendChild(grid); wrap.appendChild(res);
      function readv() { var o = {}; def.inputs.forEach(function (f) { var n = inputs[f.k]; o[f.k] = (f.t === 'sel' || f.t === 'date' || f.t === 'time' || f.t === 'text') ? n.value : parseFloat(n.value); }); return o; }
      function run() {
        var out; try { out = def.calc(readv()); } catch (e) { out = [['Error', 'Check your inputs']]; }
        res.innerHTML = ''; if (!out || !out.length) return;
        var row = el('div', { class: 'kpi-row' });
        out.forEach(function (p) { row.appendChild(CS.kpi(p[0], p[1], { class: p[2] || '' })); });
        res.appendChild(row);
      }
      setTimeout(run, 0); return wrap;
    };
  }

  var IC = { 'Financial': '\uD83D\uDCB0', 'Business': '\uD83D\uDCBC', 'Health': '\u2764\uFE0F', 'Math': '\uD83E\uDDEE', 'Date & Time': '\uD83D\uDCC5', 'Everyday': '\uD83C\uDFE0', 'Education': '\uD83C\uDF93', 'Construction': '\uD83C\uDFD7\uFE0F', 'Automotive': '\uD83D\uDE97', 'Science': '\uD83D\uDD2C' };

  var defs = [];
  function T(id, name, cat, kw, blurb, def) { defs.push({ id: id, name: name, cat: cat, kw: kw, blurb: blurb, def: def }); }

  /* ---------------- Financial (8) ---------------- */
  T('rd-maturity', 'RD Maturity Calculator', 'Financial', 'rd maturity calculator, recurring deposit maturity', 'Calculate recurring deposit maturity amount and interest earned.', { inputs: [{ k: 'p', label: 'Monthly deposit', v: 5000, step: 'any' }, { k: 'r', label: 'Interest rate (% p.a.)', v: 7, step: 'any' }, { k: 'n', label: 'Tenure (months)', v: 60, step: 1 }], calc: function (v) { var i = v.r / 1200; var fv = v.p * ((Math.pow(1 + i, v.n) - 1) / i) * (1 + i); var inv = v.p * v.n; return [['Maturity amount', fmoney(fv)], ['Invested', fmoney(inv)], ['Interest', fmoney(fv - inv)]]; } });
  T('fd-maturity', 'FD Maturity Calculator', 'Financial', 'fd maturity calculator, fixed deposit maturity', 'Find fixed deposit maturity value with compound interest.', { inputs: [{ k: 'p', label: 'Principal', v: 100000, step: 'any' }, { k: 'r', label: 'Interest rate (% p.a.)', v: 7, step: 'any' }, { k: 'y', label: 'Years', v: 5, step: 'any' }, { k: 'f', label: 'Compounding', t: 'sel', v: '4', opts: [opt('1', 'Yearly'), opt('2', 'Half-yearly'), opt('4', 'Quarterly'), opt('12', 'Monthly')] }], calc: function (v) { var f = parseFloat(v.f); var fv = v.p * Math.pow(1 + v.r / (100 * f), f * v.y); return [['Maturity amount', fmoney(fv)], ['Interest earned', fmoney(fv - v.p)]]; } });
  T('ppf-maturity', 'PPF Maturity Calculator', 'Financial', 'ppf maturity calculator, ppf return', 'Estimate PPF maturity value from yearly investment.', { inputs: [{ k: 'p', label: 'Yearly investment', v: 150000, step: 'any' }, { k: 'r', label: 'Interest rate (%)', v: 7.1, step: 'any' }, { k: 'n', label: 'Years', v: 15, step: 1 }], calc: function (v) { var i = v.r / 100; var fv = v.p * ((Math.pow(1 + i, v.n) - 1) / i) * (1 + i); var inv = v.p * v.n; return [['Maturity amount', fmoney(fv)], ['Invested', fmoney(inv)], ['Interest', fmoney(fv - inv)]]; } });
  T('gratuity', 'Gratuity Calculator', 'Financial', 'gratuity calculator, gratuity formula', 'Calculate gratuity payable from last salary and years of service.', { inputs: [{ k: 's', label: 'Last drawn salary (Basic + DA)', v: 50000, step: 'any' }, { k: 'y', label: 'Years of service', v: 10, step: 'any' }], calc: function (v) { var g = 15 * v.s * v.y / 26; return [['Gratuity amount', fmoney(g)]]; } });
  T('hra-exemption', 'HRA Exemption Calculator', 'Financial', 'hra exemption calculator, hra tax exemption', 'Find your tax-exempt HRA under the income tax rules.', { inputs: [{ k: 'basic', label: 'Basic salary (yearly)', v: 600000, step: 'any' }, { k: 'hra', label: 'HRA received (yearly)', v: 240000, step: 'any' }, { k: 'rent', label: 'Rent paid (yearly)', v: 180000, step: 'any' }, { k: 'metro', label: 'Metro city?', t: 'sel', v: 'y', opts: [opt('y', 'Yes'), opt('n', 'No')] }], calc: function (v) { var a = v.hra; var b = v.rent - 0.10 * v.basic; var c = (v.metro === 'y' ? 0.5 : 0.4) * v.basic; var ex = Math.max(0, Math.min(a, b, c)); return [['HRA exempt', fmoney(ex)], ['HRA taxable', fmoney(Math.max(0, v.hra - ex))]]; } });
  T('simple-interest-monthly', 'Monthly Simple Interest Calculator', 'Financial', 'monthly simple interest calculator', 'Calculate simple interest charged on a monthly rate.', { inputs: [{ k: 'p', label: 'Principal', v: 100000, step: 'any' }, { k: 'r', label: 'Monthly rate (%)', v: 1.5, step: 'any' }, { k: 'n', label: 'Months', v: 12, step: 1 }], calc: function (v) { var si = v.p * v.r * v.n / 100; return [['Interest', fmoney(si)], ['Total payable', fmoney(v.p + si)]]; } });
  T('credit-card-emi', 'Credit Card EMI Calculator', 'Financial', 'credit card emi calculator', 'Work out the EMI on a credit card outstanding balance.', { inputs: [{ k: 'p', label: 'Outstanding amount', v: 60000, step: 'any' }, { k: 'r', label: 'Monthly rate (%)', v: 3, step: 'any' }, { k: 'n', label: 'Months', v: 12, step: 1 }], calc: function (v) { var i = v.r / 100; var emi = i === 0 ? v.p / v.n : v.p * i * Math.pow(1 + i, v.n) / (Math.pow(1 + i, v.n) - 1); return [['Monthly EMI', fmoney(emi)], ['Total payment', fmoney(emi * v.n)], ['Total interest', fmoney(emi * v.n - v.p)]]; } });
  T('down-payment', 'Down Payment Calculator', 'Financial', 'down payment calculator', 'Split a purchase price into down payment and loan amount.', { inputs: [{ k: 'price', label: 'Total price', v: 1000000, step: 'any' }, { k: 'pct', label: 'Down payment (%)', v: 20, step: 'any' }], calc: function (v) { var dp = v.price * v.pct / 100; return [['Down payment', fmoney(dp)], ['Loan amount', fmoney(v.price - dp)]]; } });

  /* ---------------- Business (6) ---------------- */
  T('break-even', 'Break Even Point Calculator', 'Business', 'break even point calculator, break even units', 'Find the number of units to sell to cover all costs.', { inputs: [{ k: 'fc', label: 'Fixed costs', v: 100000, step: 'any' }, { k: 'price', label: 'Selling price / unit', v: 500, step: 'any' }, { k: 'vc', label: 'Variable cost / unit', v: 300, step: 'any' }], calc: function (v) { var m = v.price - v.vc; var u = m > 0 ? v.fc / m : NaN; return [['Break-even units', isFinite(u) ? fnum(Math.ceil(u), 0) : '\u2014'], ['Break-even revenue', fmoney(u * v.price)]]; } });
  T('gst-inclusive', 'GST Inclusive Price Calculator', 'Business', 'gst inclusive calculator, remove gst', 'Remove GST from an inclusive price to find base and tax.', { inputs: [{ k: 'amt', label: 'Amount (incl. GST)', v: 1180, step: 'any' }, { k: 'gst', label: 'GST rate (%)', v: 18, step: 'any' }], calc: function (v) { var base = v.amt * 100 / (100 + v.gst); return [['Base price', fmoney(base)], ['GST amount', fmoney(v.amt - base)]]; } });
  T('markup', 'Markup Calculator', 'Business', 'markup calculator, markup percentage', 'Calculate selling price and profit from cost and markup.', { inputs: [{ k: 'cost', label: 'Cost price', v: 1000, step: 'any' }, { k: 'm', label: 'Markup (%)', v: 25, step: 'any' }], calc: function (v) { var sp = v.cost * (1 + v.m / 100); return [['Selling price', fmoney(sp)], ['Profit', fmoney(sp - v.cost)]]; } });
  T('discount', 'Discount Price Calculator', 'Business', 'discount calculator, discount price', 'Find the final price and money saved after a discount.', { inputs: [{ k: 'price', label: 'Original price', v: 2000, step: 'any' }, { k: 'd', label: 'Discount (%)', v: 30, step: 'any' }], calc: function (v) { var f = v.price * (1 - v.d / 100); return [['Final price', fmoney(f)], ['You save', fmoney(v.price - f)]]; } });
  T('roi', 'ROI Calculator', 'Business', 'roi calculator, return on investment', 'Measure return on investment from cost and final value.', { inputs: [{ k: 'inv', label: 'Amount invested', v: 100000, step: 'any' }, { k: 'fin', label: 'Final value', v: 130000, step: 'any' }], calc: function (v) { var roi = (v.fin - v.inv) / v.inv * 100; return [['ROI', fnum(roi, 2) + ' %'], ['Net gain', fmoney(v.fin - v.inv)]]; } });
  T('inventory-turnover', 'Inventory Turnover Calculator', 'Business', 'inventory turnover calculator', 'Calculate inventory turnover ratio and days on hand.', { inputs: [{ k: 'cogs', label: 'Cost of goods sold', v: 1200000, step: 'any' }, { k: 'inv', label: 'Average inventory', v: 200000, step: 'any' }], calc: function (v) { var t = v.cogs / v.inv; return [['Turnover ratio', fnum(t, 2)], ['Days inventory', fnum(365 / t, 1) + ' days']]; } });

  /* ---------------- Health (6) ---------------- */
  T('bmr', 'BMR Calculator', 'Health', 'bmr calculator, basal metabolic rate', 'Estimate daily calories at rest using the Mifflin-St Jeor formula.', { inputs: [{ k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }, { k: 'h', label: 'Height (cm)', v: 170, step: 'any' }, { k: 'age', label: 'Age', v: 30, step: 1 }, { k: 'g', label: 'Gender', t: 'sel', v: 'm', opts: [opt('m', 'Male'), opt('f', 'Female')] }], calc: function (v) { var b = 10 * v.w + 6.25 * v.h - 5 * v.age + (v.g === 'm' ? 5 : -161); return [['BMR', fnum(b, 0) + ' kcal/day'], ['Maintenance (light activity)', fnum(b * 1.375, 0) + ' kcal']]; } });
  T('body-fat', 'Body Fat Percentage Calculator', 'Health', 'body fat calculator, navy body fat', 'Estimate body fat percentage using the US Navy method.', { inputs: [{ k: 'g', label: 'Gender', t: 'sel', v: 'm', opts: [opt('m', 'Male'), opt('f', 'Female')] }, { k: 'h', label: 'Height (cm)', v: 175, step: 'any' }, { k: 'neck', label: 'Neck (cm)', v: 38, step: 'any' }, { k: 'waist', label: 'Waist (cm)', v: 85, step: 'any' }, { k: 'hip', label: 'Hip (cm, women)', v: 95, step: 'any' }], calc: function (v) { var bf; if (v.g === 'm') bf = 495 / (1.0324 - 0.19077 * Math.log10(v.waist - v.neck) + 0.15456 * Math.log10(v.h)) - 450; else bf = 495 / (1.29579 - 0.35004 * Math.log10(v.waist + v.hip - v.neck) + 0.22100 * Math.log10(v.h)) - 450; return [['Body fat', fnum(bf, 1) + ' %']]; } });
  T('ideal-weight', 'Ideal Weight Calculator', 'Health', 'ideal weight calculator', 'Estimate ideal body weight from height using the Devine formula.', { inputs: [{ k: 'h', label: 'Height (cm)', v: 170, step: 'any' }, { k: 'g', label: 'Gender', t: 'sel', v: 'm', opts: [opt('m', 'Male'), opt('f', 'Female')] }], calc: function (v) { var inch = v.h / 2.54; var base = v.g === 'm' ? 50 : 45.5; var w = base + 2.3 * Math.max(0, inch - 60); return [['Ideal weight', fnum(w, 1) + ' kg']]; } });
  T('water-intake', 'Daily Water Intake Calculator', 'Health', 'water intake calculator, daily water', 'Find how much water to drink daily based on your weight.', { inputs: [{ k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }, { k: 'ex', label: 'Exercise (minutes/day)', v: 30, step: 1 }], calc: function (v) { var l = v.w * 0.033 + (v.ex / 30) * 0.35; return [['Daily water', fnum(l, 2) + ' litres'], ['Glasses (250ml)', fnum(l * 1000 / 250, 0)]]; } });
  T('calories-burned-walking', 'Calories Burned Walking Calculator', 'Health', 'calories burned walking calculator', 'Estimate calories burned while walking for a set time.', { inputs: [{ k: 'w', label: 'Weight (kg)', v: 70, step: 'any' }, { k: 'min', label: 'Minutes', v: 30, step: 1 }, { k: 'met', label: 'Pace', t: 'sel', v: '3.5', opts: [opt('2.8', 'Slow (3 km/h)'), opt('3.5', 'Moderate (5 km/h)'), opt('5', 'Brisk (6.5 km/h)'), opt('7', 'Fast (8 km/h)')] }], calc: function (v) { var met = parseFloat(v.met); var cal = met * 3.5 * v.w / 200 * v.min; return [['Calories burned', fnum(cal, 0) + ' kcal']]; } });
  T('pregnancy-due-date', 'Pregnancy Due Date Calculator', 'Health', 'due date calculator, pregnancy due date', 'Estimate your due date from the last menstrual period.', { inputs: [{ k: 'lmp', label: 'Last period date', t: 'date', v: '' }], calc: function (v) { var d = pdate(v.lmp); if (!d) return [['Due date', 'Pick a date']]; var due = new Date(d.getTime() + 280 * 86400000); var wk = Math.floor((Date.now() - d.getTime()) / (7 * 86400000)); return [['Due date', due.toDateString()], ['Weeks pregnant', (wk >= 0 ? wk : 0) + ' weeks']]; } });

  /* ---------------- Math (6) ---------------- */
  T('lcm-hcf', 'LCM and HCF Calculator', 'Math', 'lcm hcf calculator, lcm gcd', 'Find the LCM and HCF (GCD) of two numbers.', { inputs: [{ k: 'a', label: 'First number', v: 12, step: 1 }, { k: 'b', label: 'Second number', v: 18, step: 1 }], calc: function (v) { var g = gcd(v.a, v.b); return [['HCF (GCD)', fnum(g, 0)], ['LCM', fnum(Math.abs(v.a * v.b) / g, 0)]]; } });
  T('percentage-increase', 'Percentage Increase Calculator', 'Math', 'percentage increase calculator', 'Calculate percentage change between two values.', { inputs: [{ k: 'from', label: 'Original value', v: 200, step: 'any' }, { k: 'to', label: 'New value', v: 260, step: 'any' }], calc: function (v) { var p = (v.to - v.from) / v.from * 100; return [[p >= 0 ? 'Increase' : 'Decrease', fnum(Math.abs(p), 2) + ' %'], ['Difference', fnum(v.to - v.from, 2)]]; } });
  T('ratio', 'Ratio Calculator', 'Math', 'ratio calculator, simplify ratio', 'Simplify a ratio to its lowest whole-number terms.', { inputs: [{ k: 'a', label: 'Value A', v: 40, step: 'any' }, { k: 'b', label: 'Value B', v: 60, step: 'any' }], calc: function (v) { var g = gcd(v.a, v.b) || 1; return [['Simplified ratio', fnum(v.a / g, 0) + ' : ' + fnum(v.b / g, 0)], ['Decimal', fnum(v.a / v.b, 3)]]; } });
  T('average', 'Average Calculator', 'Math', 'average calculator, mean calculator', 'Find the mean of a list of numbers.', { inputs: [{ k: 'nums', label: 'Numbers (comma separated)', t: 'text', v: '10, 20, 30, 40' }], calc: function (v) { var a = LIST(v.nums); if (!a.length) return [['Average', '\u2014']]; var s = a.reduce(function (x, y) { return x + y; }, 0); return [['Average', fnum(s / a.length, 3)], ['Sum', fnum(s, 3)], ['Count', a.length]]; } });
  T('cube-root', 'Cube Root Calculator', 'Math', 'cube root calculator', 'Find the cube root of any number.', { inputs: [{ k: 'n', label: 'Number', v: 27, step: 'any' }], calc: function (v) { return [['Cube root', fnum(Math.cbrt(v.n), 6)]]; } });
  T('exponent', 'Exponent Calculator', 'Math', 'exponent calculator, power calculator', 'Raise a base to any power.', { inputs: [{ k: 'b', label: 'Base', v: 2, step: 'any' }, { k: 'p', label: 'Exponent', v: 10, step: 'any' }], calc: function (v) { return [['Result', fnum(Math.pow(v.b, v.p), 6)]]; } });

  /* ---------------- Date & Time (3) ---------------- */
  T('age-in-days', 'Age in Days Calculator', 'Date & Time', 'age in days calculator', 'Find your exact age in days from your date of birth.', { inputs: [{ k: 'dob', label: 'Date of birth', t: 'date', v: '' }], calc: function (v) { var d = pdate(v.dob); if (!d) return [['Days', 'Pick a date']]; var days = Math.floor((Date.now() - d.getTime()) / 86400000); return [['Age in days', fnum(days, 0)], ['Age in weeks', fnum(days / 7, 0)], ['Age in months', fnum(days / 30.4375, 0)]]; } });
  T('days-between-dates', 'Days Between Dates Calculator', 'Date & Time', 'days between dates calculator', 'Count the number of days between two dates.', { inputs: [{ k: 'd1', label: 'Start date', t: 'date', v: '' }, { k: 'd2', label: 'End date', t: 'date', v: '' }], calc: function (v) { var a = pdate(v.d1), b = pdate(v.d2); if (!a || !b) return [['Days', 'Pick both dates']]; var days = Math.round((b.getTime() - a.getTime()) / 86400000); return [['Days', fnum(Math.abs(days), 0)], ['Weeks', fnum(Math.abs(days) / 7, 1)]]; } });
  T('reading-time', 'Reading Time Calculator', 'Date & Time', 'reading time calculator', 'Estimate how long a text takes to read.', { inputs: [{ k: 'words', label: 'Word count', v: 1200, step: 1 }, { k: 'wpm', label: 'Reading speed (wpm)', v: 200, step: 1 }], calc: function (v) { var m = v.words / v.wpm; return [['Reading time', fnum(m, 1) + ' min'], ['At 150 wpm', fnum(v.words / 150, 1) + ' min']]; } });

  /* ---------------- Everyday (5) ---------------- */
  T('tip', 'Tip Calculator', 'Everyday', 'tip calculator, tip split', 'Calculate a tip and split the bill between people.', { inputs: [{ k: 'bill', label: 'Bill amount', v: 1200, step: 'any' }, { k: 'tip', label: 'Tip (%)', v: 10, step: 'any' }, { k: 'people', label: 'People', v: 2, step: 1 }], calc: function (v) { var tip = v.bill * v.tip / 100; var total = v.bill + tip; return [['Tip', fmoney(tip)], ['Total', fmoney(total)], ['Per person', fmoney(total / Math.max(1, v.people))]]; } });
  T('fuel-cost', 'Fuel Cost Calculator', 'Everyday', 'fuel cost calculator, trip fuel cost', 'Estimate the fuel cost of a trip.', { inputs: [{ k: 'dist', label: 'Distance (km)', v: 500, step: 'any' }, { k: 'mileage', label: 'Mileage (km/L)', v: 18, step: 'any' }, { k: 'price', label: 'Fuel price / litre', v: 100, step: 'any' }], calc: function (v) { var l = v.dist / v.mileage; return [['Fuel needed', fnum(l, 2) + ' L'], ['Fuel cost', fmoney(l * v.price)]]; } });
  T('electricity-bill', 'Electricity Bill Calculator', 'Everyday', 'electricity bill calculator, units cost', 'Estimate an electricity bill from units consumed.', { inputs: [{ k: 'units', label: 'Units consumed (kWh)', v: 300, step: 'any' }, { k: 'rate', label: 'Rate per unit', v: 8, step: 'any' }, { k: 'fixed', label: 'Fixed charges', v: 100, step: 'any' }], calc: function (v) { return [['Energy charge', fmoney(v.units * v.rate)], ['Total bill', fmoney(v.units * v.rate + v.fixed)]]; } });
  T('unit-price', 'Unit Price Calculator', 'Everyday', 'unit price calculator, price per unit', 'Compare value by calculating price per unit.', { inputs: [{ k: 'price', label: 'Total price', v: 250, step: 'any' }, { k: 'qty', label: 'Quantity', v: 5, step: 'any' }], calc: function (v) { return [['Price per unit', fmoney(v.price / v.qty)]]; } });
  T('discount-stacked', 'Double Discount Calculator', 'Everyday', 'double discount calculator, stacked discount', 'Apply two successive discounts and see the effective rate.', { inputs: [{ k: 'price', label: 'Original price', v: 2000, step: 'any' }, { k: 'd1', label: 'First discount (%)', v: 20, step: 'any' }, { k: 'd2', label: 'Second discount (%)', v: 10, step: 'any' }], calc: function (v) { var f = v.price * (1 - v.d1 / 100) * (1 - v.d2 / 100); return [['Final price', fmoney(f)], ['Effective discount', fnum((1 - f / v.price) * 100, 2) + ' %']]; } });

  /* ---------------- Education (3) ---------------- */
  T('marks-percentage', 'Marks Percentage Calculator', 'Education', 'marks percentage calculator', 'Convert obtained marks into a percentage.', { inputs: [{ k: 'obt', label: 'Marks obtained', v: 425, step: 'any' }, { k: 'total', label: 'Total marks', v: 500, step: 'any' }], calc: function (v) { return [['Percentage', fnum(v.obt / v.total * 100, 2) + ' %']]; } });
  T('cgpa-to-percentage', 'CGPA to Percentage Calculator', 'Education', 'cgpa to percentage calculator', 'Convert CGPA to a percentage (x 9.5 rule).', { inputs: [{ k: 'cgpa', label: 'CGPA', v: 8.2, step: 'any' }, { k: 'factor', label: 'Multiplier', v: 9.5, step: 'any' }], calc: function (v) { return [['Percentage', fnum(v.cgpa * v.factor, 2) + ' %']]; } });
  T('gpa', 'GPA Calculator', 'Education', 'gpa calculator', 'Average your grade points into a GPA.', { inputs: [{ k: 'pts', label: 'Grade points (comma separated)', t: 'text', v: '8, 9, 7, 10' }], calc: function (v) { var a = LIST(v.pts); if (!a.length) return [['GPA', '\u2014']]; return [['GPA', fnum(a.reduce(function (x, y) { return x + y; }, 0) / a.length, 2)], ['Subjects', a.length]]; } });

  /* ---------------- Construction / Automotive / Science (3) ---------------- */
  T('paint-quantity', 'Paint Quantity Calculator', 'Construction', 'paint calculator, paint quantity', 'Estimate litres of paint needed for a wall area.', { inputs: [{ k: 'area', label: 'Wall area (sq ft)', v: 800, step: 'any' }, { k: 'coverage', label: 'Coverage (sq ft / L)', v: 120, step: 'any' }, { k: 'coats', label: 'Coats', v: 2, step: 1 }], calc: function (v) { var l = v.area * v.coats / v.coverage; return [['Paint needed', fnum(l, 1) + ' litres']]; } });
  T('tile-count', 'Tile Calculator', 'Construction', 'tile calculator, tiles needed', 'Estimate tiles needed for a floor, with wastage.', { inputs: [{ k: 'room', label: 'Room area (sq ft)', v: 200, step: 'any' }, { k: 'tile', label: 'Tile area (sq ft)', v: 4, step: 'any' }, { k: 'waste', label: 'Wastage (%)', v: 10, step: 'any' }], calc: function (v) { var n = Math.ceil(v.room / v.tile * (1 + v.waste / 100)); return [['Tiles needed', fnum(n, 0)]]; } });
  T('speed-distance-time', 'Speed Distance Time Calculator', 'Automotive', 'speed distance time calculator', 'Calculate average speed from distance and time.', { inputs: [{ k: 'dist', label: 'Distance (km)', v: 240, step: 'any' }, { k: 'time', label: 'Time (hours)', v: 4, step: 'any' }], calc: function (v) { var s = v.dist / v.time; return [['Average speed', fnum(s, 2) + ' km/h'], ['In m/s', fnum(s / 3.6, 2) + ' m/s']]; } });

  /* ===================== REGISTER + AUTO SEO ===================== */
  function slugFor(id) { return id + '-calculator'; }
  function relatedFor(cat, id) { var r = []; for (var i = 0; i < defs.length && r.length < 4; i++) { if (defs[i].cat === cat && defs[i].id !== id) r.push(defs[i].id); } return r; }
  function faqsFor(name) { return [{ q: 'How do I use the ' + name + '?', a: 'Enter your values in the fields above and the ' + name + ' updates the result instantly \u2014 no sign-up needed.' }, { q: 'Is the ' + name + ' free?', a: 'Yes. It is completely free with no limits and no account required.' }, { q: 'Does it work on mobile?', a: 'Yes. It runs in your browser and works on phones, tablets and desktops.' }]; }

  defs.forEach(function (d) {
    var icon = IC[d.cat] || '\uD83E\uDDEE';
    if (root.CS && root.CS.Calc && typeof root.CS.Calc.register === 'function') {
      root.CS.Calc.register({ id: d.id, name: d.name, category: d.cat, icon: icon, description: d.blurb, render: simple(d.def) });
    }
    if (!SEO.TOOLS[d.id]) {
      SEO.TOOLS[d.id] = { slug: slugFor(d.id), cat: d.cat, icon: icon, name: d.name, title: d.name + ' \u2013 Free Online Calculator', desc: d.blurb, keywords: d.kw, intro: d.blurb + ' This free tool works instantly in your browser on any device, with no sign-up required.', options: (d.def.inputs || []).map(function (f) { return f.label; }), faqs: faqsFor(d.name), related: relatedFor(d.cat, d.id) };
      if (SEO.ORDER && SEO.ORDER.indexOf(d.id) === -1) SEO.ORDER.push(d.id);
    }
  });

  if (typeof module !== 'undefined' && module.exports) { module.exports = SEO; }
})(typeof window !== 'undefined' ? window : globalThis);
